/* =========================================================
   RathnaHub – data.js
   1) FIELD_DEFS : the 20 rows shown on every gem sheet
                   (same order as the book page).
   2) GEMS       : one object per gem. Add all 105 here.

   A value can be:
     "text"                         -> same in both languages
     { en: "text", si: "සිංහල" }     -> bilingual value
     ""  (or missing)               -> shown as "—"
   ========================================================= */

const FIELD_DEFS = [
  { key: "formula",      en: "Formula",              si: "රසායනික සූත්‍රය" },
  { key: "composition",  en: "Chemical Composition", si: "රසායනික සංයුතිය" },
  { key: "crystal",      en: "Crystal System",       si: "ස්ඵටික පද්ධතිය" },
  { key: "group",        en: "Group",                si: "කාණ්ඩය" },
  { key: "lustre",       en: "Lustre",               si: "දීප්තිය" },
  { key: "ri",           en: "Refractive Indices",   si: "වර්තනාංක" },
  { key: "optic",        en: "Optical Sign",         si: "දෘෂ්ටික ලකුණ" },
  { key: "colour",       en: "Colour",               si: "වර්ණය" },
  { key: "absorption",   en: "Absorption Spectrum",  si: "අවශෝෂණ වර්ණාවලිය" },
  { key: "inclusions",   en: "Inclusions",           si: "අන්තර්ගත" },
  { key: "birefringence",en: "Birefringence",        si: "ද්විවර්තනය" },
  { key: "sg",           en: "Specific Gravity",     si: "විශිෂ්ට ගුරුත්වය" },
  { key: "hardness",     en: "Hardness",             si: "දෘඪතාව" },
  { key: "dispersion",   en: "Dispersion",           si: "වර්ණ ව්‍යාප්තිය" },
  { key: "dichroism",    en: "Dichroism",            si: "ද්වීවර්ණතාව" },
  { key: "transparency", en: "Transparency",         si: "පාරදෘශ්‍යතාව" },
  { key: "locality",     en: "Locality Occurrence",  si: "ඇතිවන ස්ථාන" },
  { key: "discoverer",   en: "Discoverer",           si: "සොයාගත් අය" },
  { key: "comments",     en: "Comments",             si: "අමතර තොරතුරු" },
  { key: "year",         en: "Discovered Year",      si: "සොයාගත් වර්ෂය" }
];

/* "swatch" = a hex colour used to tint the gem icon and card.
   "no"     = the number printed in the book (01, 02, ...). */
const GEMS = [
    {
    id: "actinolite",
    no: 1,
    swatch: "#5E8C6A",
    name: { en: "Actinolite", si: "ඇක්ටිනෝලයිට්" },
    group: "Amphibole",
    fields: {
      formula: "Ca2(Mg,Fe)5(OH)2(Si4O11)2",
      composition: "Calcium, Magnesium, Iron Silicate",
      crystal: "Monoclinic",
      group: "Amphibole",
      lustre: "Vitreous",
      ri: "1.620 – 1.642",
      optic: "B-",
      colour: { en: "Light & Dark Green – Brown", si: "ලා සහ තද කොළ – දුඹුරු" },
      absorption: { en: "A weak line at 503 nm", si: "දුර්වල රේඛාවක් 503nm හි ඇත." },
      inclusions: { en: "Fibre-like inclusions; solid and liquid inclusions", si: "කෙඳි මෙන් අන්තර්ගත, ඝන ද්‍රව තාරායම්" },
      birefringence: "0.022",
      sg: "3.05",
      hardness: "5½",
      dispersion: "",
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Actinolite crystals occur on dolomite rock together with biotite mica. Balangoda, Tanzania", si: "ඩොලමයිට් ගල මතුපිට, බයෝටයිට් මයිකා සමඟ ඇක්ටිනෝලයිට් ස්ඵටික පිහිටා ඇත. බලංගොඩ. ටැන්සානියාව" },
      discoverer: "Richard Kirwan",
      comments: { en: "aktis = ray. Tends to split off in flakes; single-thread (fibrous) forms also occur.", si: "aktis = ray. පතුරු ගැලවෙන ගතිය ඇත. තනි නූල වෛරෝඩි ද ඇත" },
      year: "1794"
    }
  },
  {
    id: "almandine-garnet",
    no: 2,
    swatch: "#8B1A2B",
    name: { en: "Almandine Garnet", si: "ඇල්මන්ඩීන් රබහ" },
    group: "Garnet",
    fields: {
      formula: "Fe3Al2(SiO4)3",
      composition: "Iron, Aluminium, Silicate",
      crystal: "Cubic",
      group: "Garnet",
      lustre: "Vitreous",
      ri: "1.76 – 1.82",
      optic: "",
      colour: { en: "Blood Red", si: "තද රතු" },
      absorption: { en: "3 strong bands: 576, 526, 505 nm", si: "ප්‍රබල රේඛා 3 ඇත. 576, 526, 505 nm" },
      inclusions: "",
      birefringence: "",
      sg: "3.8 – 4.2",
      hardness: "7½",
      dispersion: "0.027",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Alabanda, Turkey / Elahera, Sri Lanka / Madagascar / Africa", si: "Alabanda, Turkey / Elahera, Sri Lanka / Madagaskar / Africa" },
      discoverer: "Agricola 1546 & Karsten",
      comments: { en: "Garnet; star and single-thread varieties also occur", si: "රබහ, ආනුල් සහ තනි නූල වෛරෝඩි ද ඇත" },
      year: "1794"
    }
  },
  {
    id: "amblygonite",
    no: 3,
    swatch: "#D9C84A",
    name: { en: "Amblygonite", si: "ඇම්බ්ලිගෝනයිට්" },
    group: "Tilasite",
    fields: {
      formula: "LiAl(PO4)F",
      composition: "Lithium, Aluminium, Fluorine, Phosphate",
      crystal: "Triclinic",
      group: "Tilasite",
      lustre: "Vitreous",
      ri: "1.611 – 1.637",
      optic: "B+",
      colour: { en: "Colourless, Yellow, Pink", si: "අවර්ණ, කහ, රෝස" },
      absorption: "",
      inclusions: "",
      birefringence: "0.026",
      sg: "3.01",
      hardness: "6",
      dispersion: { en: "Sharp", si: "තියුණුයි" },
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found inside hard rock. Balangoda / Brazil, France, Namibia", si: "කළුගල් ඇතුලත. බලංගොඩ./ බ්‍රසීලය, ප්‍රංශය, නැම්බියාව" },
      discoverer: "",
      comments: { en: "A rare gemstone. Greek name amblygonite ('blunt angle', from the crystal shape). Yellow crystal, 254 ct.", si: "දුර්ලභ මැණික් ගලකි. ස්ඵටික ස්වරූපය, මුවාත නැති, කෝණ ඇත. ග්‍රීක් නම ඇම්බ්ලිගෝනයිට්. ස්ඵටිකය කහ, 254 ක්‍රාත්." },
      year: "1817"
    }
  },
  {
    id: "andalusite",
    no: 4,
    swatch: "#7A8B3A",
    name: { en: "Andalusite", si: "ඇන්ඩලුසයිට්" },
    group: "Andalusite",
    fields: {
      formula: "Al2SiO5",
      composition: "Aluminium, Silicate",
      crystal: "Orthorhombic",
      group: "Andalusite",
      lustre: "",
      ri: "1.634 – 1.641 / 1.644 – 1.648",
      optic: "B-",
      colour: { en: "Green mixed with pink", si: "කොළ මිශ්‍ර රෝස" },
      absorption: { en: "Sharp lines at 5505, 5475 Å, 5535 Å", si: "තියුණු රේඛාවල් ඇත 5505, 5475Å, 5535Å" },
      inclusions: "",
      birefringence: "0.007 – 0.011",
      sg: "3.17",
      hardness: "7½",
      dispersion: "0.016",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රබලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Andalusia province, Spain. Nawalapitiya, Ginigathhena (Sri Lanka), Madagascar.", si: "ඇඩුලූසියා ප්‍රාන්තය, Spain. නාවලපිටිය, ගිනිගත්හේන ශ්‍රී ලංකාව, මැඩගස්කරය." },
      discoverer: "",
      comments: { en: "Polymorphous with sillimanite and kyanite, all sharing the formula Al2SiO5. A rare gemstone; some people are fooled into calling it alexandrite.", si: "Polymorphous පොලිමෝෆස්-සිලිමනයිට් සහ කයනයිට් එම සූත්‍රය ඇත Al2SiO5. ගිනිබොකුතෝර ගැම්නම. දුර්ලභ මැණික් ගලකි.සමහර අය පසිංගලයක් කියා රැවටෙති." },
      year: "1789"
    }
  },
  {
    id: "anglesite",
    no: 5,
    swatch: "#E0A040",
    name: { en: "Anglesite", si: "ඇන්ග්ලිසයිට්" },
    group: "Barite",
    fields: {
      formula: "PbSO4",
      composition: "Lead Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Adamantine",
      ri: "1.877 – 1.894",
      optic: "B+",
      colour: { en: "Colourless, Yellow, Green, Orange, Blue", si: "අවර්ණ, කහ, කොළ, තැඹිලි, නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.017",
      sg: "6.38",
      hardness: "3",
      dispersion: "0.044",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රහලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "In Wales at Parys Mine – Island of Anglesey", si: "In Wales at Parys Mine – Island of Anglesey" },
      discoverer: "",
      comments: { en: "A foreign (imported) stone.", si: "පිටරට ගලකි." },
      year: "1832"
    }
  },
  {
    id: "apatite",
    no: 6,
    swatch: "#2FB5A0",
    name: { en: "Apatite", si: "ඇපටයිට්" },
    group: "Apatite",
    fields: {
      formula: "Ca(F,Cl)Ca4(PO4)",
      composition: "Calcium, Fluorine Phosphate",
      crystal: "Hexagonal",
      group: "Apatite",
      lustre: "Vitreous",
      ri: "1.63 – 1.64",
      optic: "U-",
      colour: { en: "White, Yellow, Green, Blue, Violet, Brown", si: "සුදු, කහ, කොළ, නිල්, දම්, දුඹුරු" },
      absorption: { en: "7 lines at 5800 Å; 5 lines at 5200 Å (didymium). Blue apatite: 5120, 4910, 4640 Å", si: "රේඛා 7ක් 5800Å හි ඇත. රේඛා 5ක් 5200Å හි ඇත. (ඩිඩිමියම්) නිල් ඇපටයිට් - 5120, 4910, 4640Å" },
      inclusions: "",
      birefringence: "0.002 – 0.004",
      sg: "3.18",
      hardness: "5",
      dispersion: "0.013",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රබලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Blue apatite crystals occur within white calcite rock. Balangoda, Madagascar.", si: "සුදු කැල්සයිට් ගල තුල නිල් ඇපටයිට ස්ඵටික පිහිටා ඇත. බලංගොඩ. මැඩගස්කරය." },
      discoverer: "",
      comments: { en: "Apatite varieties also occur. Greek 'apatao' = to deceive: it is easily mistaken for other gems (e.g. aquamarine/beryl).", si: "ඇපටයිට් වෛරෝඩි ඇත. ග්‍රීක් deceive රැවටෙනවා ඇකමරින් (බෙරිල්)" },
      year: "1788"
    }
  },
  {
    id: "azurite",
    no: 7,
    swatch: "#2B4FB0",
    name: { en: "Azurite", si: "ඇසුරයිට්" },
    group: "Halogen",
    fields: {
      formula: "Cu3(OH)2(CO)2",
      composition: "Copper Carbonate",
      crystal: "Monoclinic",
      group: "Halogen",
      lustre: "Vitreous",
      ri: "1.73 – 1.84",
      optic: "B+",
      colour: { en: "Azure Blue", si: "ඇසුරු නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.110",
      sg: "3.77 – 3.88",
      hardness: "4",
      dispersion: "",
      dichroism: "",
      transparency: { en: "Opaque", si: "පාරාන්ධ" },
      locality: { en: "Found within copper deposits in Australia, Mexico, France and Arizona.", si: "ඕස්ට්‍රේලියාව, මෙක්සිකෝ, ප්‍රංශය, ඇරිසෝනා කොපර් නිධි තුළ හමුවේ ඇත." },
      discoverer: "",
      comments: { en: "A foreign gemstone. Has cleavage in one direction. Persian lazhward = blue colour.", si: "පිටරට මැණික් ගලකි. එක් පැත්තකට පැලුම ඇත. Persian lazhward, blue colour තේරුම නිල් වර්ණය" },
      year: "Ancient times"
    }
  },
  {
    id: "baddeleyite",
    no: 8,
    swatch: "#3A3A34",
    name: { en: "Baddeleyite", si: "බැඩ්ලියිට්" },
    group: "Rutile",
    fields: {
      formula: "ZrO2",
      composition: "Zirconium Oxide",
      crystal: "Monoclinic",
      group: "Rutile",
      lustre: "Vitreous – Greasy",
      ri: "2.136 – 2.243",
      optic: "B-",
      colour: { en: "Black, Red, Yellow, Green, Colourless", si: "කළු, රතු, කහ, කොළ, අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.107",
      sg: "5.82",
      hardness: "6½",
      dispersion: "",
      dichroism: { en: "Strong: dark brown / brown / light brown", si: "ප්‍රබලය තද දුඹුරු / දුඹුරු / ලා දුඹුරු" },
      transparency: { en: "Opaque", si: "පාරාන්ධ" },
      locality: { en: "Rakwana, Balangoda. Identified and reported from Sri Lanka. Mt. Somma, Italy.", si: "රක්වාන, බලංගොඩ. ශ්‍රී ලංකාවෙන් සොයා ඉදිරිපත් කර ඇත. සෝමා කන්ද, ඉතාලිය." },
      discoverer: "Joseph Baddeley",
      comments: { en: "Has cleavage. A very rare gemstone. Streak colour: brownish grey.", si: "පැලුම ඇත. අති දුර්ලභ මැණික් ගලකි. කුඩු වර්ණය : දුඹුරු අළු" },
      year: "1892"
    }
  },
  {
    id: "barite",
    no: 9,
    swatch: "#D6B25A",
    name: { en: "Barite", si: "බේරයිට්" },
    group: "Barite",
    fields: {
      formula: "BaSO4",
      composition: "Barium Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Vitreous",
      ri: "1.636 – 1.648",
      optic: "B+",
      colour: { en: "Yellow, Green, Red, Blue, Brown, White", si: "කහ, කොළ, රතු, නිල්, දුඹුරු, සුදු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.012",
      sg: "4.47",
      hardness: "3",
      dispersion: "0.016",
      dichroism: { en: "Weak", si: "දුර්වලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: "",
      discoverer: "",
      comments: { en: "Shows a pale green-blue fluorescence under ultraviolet light. Greek 'baros' = heavy spar; a heavy gemstone.", si: "පාරජම්බුල කිරණ තුළ ලා කොළ නිල් ප්‍රදීපනයක් පෙන්නුම් කරයි. Greek Baros heavy Spar" },
      year: "1640"
    }
  },
  {
    id: "benitoite",
    no: 10,
    swatch: "#2F4FBF",
    name: { en: "Benitoite", si: "බෙනිටොයිට්" },
    group: "Benitoite",
    fields: {
      formula: "BaTiSi3O9",
      composition: "Barium Titanium Silicate",
      crystal: "Hexagonal",
      group: "Benitoite",
      lustre: "Vitreous",
      ri: "1.757 – 1.804",
      optic: "U-",
      colour: { en: "Sapphire blue, Colourless", si: "සපයර් නිල් වර්ණය, අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.047",
      sg: "3.64",
      hardness: "6½",
      dispersion: "0.047",
      dichroism: { en: "Strong, blue / violet", si: "ප්‍රබලය නිල් / දම්" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found within igneous rock. San Benito River, California, USA", si: "ආග්නේය පාෂාණය තුළ පිහිටයි. San Benito river, Califonia, USA" },
      discoverer: "",
      comments: { en: "Named after the place where it was found. A foreign stone; shows strong blue fluorescence under short-wave ultraviolet light. A rare gemstone.", si: "හමුවුනු ස්ථානයේ නම යොදා ඇත. පිටරට ගලකි. කෙටි තරංග පාරජම්බුල කිරණ තුළ ප්‍රබල නිල් ප්‍රදීපයකින් පෙන්නුම් කරයි. දුර්ලභ මැණික් ගලකි." },
      year: "1907"
    }
  },
  {
    id: "beryl",
    no: 11,
    swatch: "#4CB58A",
    name: { en: "Beryl", si: "බෙරිල්" },
    group: "Beryl",
    fields: {
      formula: "Be3Al2(SiO3)6",
      composition: "Beryllium, Aluminium, Silicate",
      crystal: "Hexagonal",
      group: "Beryl",
      lustre: "Vitreous",
      ri: "1.57 – 1.58",
      optic: "U-",
      colour: {
        en: "Emerald – Grass Green; Aquamarine – Bluish Green; Morganite – Pink; Goshenite – Colourless; Heliodor – Yellow",
        si: "මරකත - තණකොළ පාට; ඇකමරින් (නිල් තරප්පු) - නිල් මිශ්‍ර කොළ, මුහුදු වතුර පාට; මෝගනයිට් - රෝස පාට; ගොෂෙනයිට් - අවර්ණ; හෙලියඩෝ - කහ"
      },
      absorption: { en: "Emerald: 2 strong lines (doublet) at 680 and 637 nm; also a line at 477 nm.", si: "එමරල්ඩ් ප්‍රබල රේඛා 2 ඇත. (doublet) 680 සහ 637. තින් රේඛාවක් 477 nm හි ඇත." },
      inclusions: { en: "3-phase inclusions in emerald", si: "3 phase inclusions in Emerald" },
      birefringence: "0.006",
      sg: "2.70",
      hardness: "7½",
      dispersion: "",
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Aquamarine occurs in pegmatite crystals. Ratnapura, Madagascar, Brazil.", si: "ඇකමරින් - පළිඟු ස්ඵටික තුළ පිහිටා ඇත. රත්නපුර, මැඩගස්කරය, බ්‍රසීලය." },
      discoverer: "",
      comments: { en: "Shows a pale green-blue fluorescence under ultraviolet light. Name from Greek 'beryllos'.", si: "පාරජම්බුල කිරණ තුළ ලා කොළ නිල් ප්‍රදීපනයක් පෙන්නුම් කරයි. බෙරිලෝස්" },
      year: "Ancient times"
    }
  },
  {
    id: "beryllonite",
    no: 12,
    swatch: "#E4DDA0",
    name: { en: "Beryllonite", si: "බෙරිලෝනයිට්" },
    group: "Phosphate",
    fields: {
      formula: "NaBePO4",
      composition: "Beryllium, Sodium, Phosphate",
      crystal: "Monoclinic",
      group: "Phosphate",
      lustre: "Vitreous",
      ri: "1.553 – 1.562",
      optic: "B-",
      colour: { en: "Colourless, White, Pale Yellow", si: "අවර්ණ, සුදු, ලා කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.009",
      sg: "2.85",
      hardness: "5",
      dispersion: "0.010",
      dichroism: { en: "None", si: "නැත" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Stoneham, Maine, USA – in hard-rock cavities", si: "Stoneham, Main, USA කළුගල් කුහර තුළ" },
      discoverer: "",
      comments: { en: "A foreign stone. No colour change under ultraviolet light. A rare gemstone. Named for its beryllium content.", si: "පිටරට ගලකි. පාරජම්බුල කිරණ තුළ වර්ණවත් වෙනසක් නොමැත. දුර්ලභ මැණික් ගලකි. බෙරිලියම් සූත්‍රයේ ඇති නිසා නම දී ඇත." },
      year: "1888"
    }
  },
  {
    id: "bonnynite",
    no: 13,
    swatch: "#2E9C84",
    name: { en: "Bonnynite", si: "බොනීනයිට්" },
    group: "Aenigmatite",
    fields: {
      formula: "(Ca,Na)2(Al,Mg,Fe2+,Fe3+)6(Si,B,Al)6O20",
      composition: "Calcium, Sodium, Aluminium, Magnesium, Iron, Boron Oxide",
      crystal: "Triclinic",
      group: "Aenigmatite",
      lustre: "Vitreous",
      ri: "α 1.697, β 1.700, γ 1.702",
      optic: "B-",
      colour: { en: "Bluish Green", si: "නිල මිශ්‍ර කොළ" },
      absorption: { en: "One strong line at 470", si: "එක් ප්‍රබල රේඛාවක් 470 හි ඇත." },
      inclusions: { en: "White marked crystals, 2 parallel lines. Polysynthetic twinned", si: "සුදු සළකුණු ස්ඵටික, සමාන්තර ඉරි 2. Polysynthetic Twinned" },
      birefringence: "0.005",
      sg: "3.44",
      hardness: "7",
      dispersion: "0.025",
      dichroism: { en: "Strong: yellow, blue, green", si: "ප්‍රබලය / කහ, නිල්, කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Ginigalgoda, Kolonna, Sri Lanka", si: "ගිනිගල්ගොඩ, කොලොන්න, ශ්‍රී ලංකාව" },
      discoverer: "Dr. Dunil Palitha Gunasekara (Gemmologist)",
      comments: { en: "A new gemstone. Named after his mother's first name, Bonny. The name Bonnynite was approved by D.G. Minatidis, a scientist from Greece. Named in 2000.", si: "අළුත් මැණික් ගලකි. කතෘ ගේ මවගේ මුල් නම බොනි. ග්‍රීසියේ D.G. Minatidis නම් විද්‍යාඥයා විසින් බොනීනයිට් නම අනුමත කර ඇත." },
      year: "1996"
    }
  },
  {
    id: "brazilianite",
    no: 14,
    swatch: "#B9C243",
    name: { en: "Brazilianite", si: "බ්‍රසීල්නයිට්" },
    group: "Vilasite",
    fields: {
      formula: "NaAl3(PO4)2(OH)4",
      composition: "Hydrous Sodium, Aluminium, Phosphate",
      crystal: "Monoclinic",
      group: "Vilasite",
      lustre: "Vitreous",
      ri: "1.603 – 1.623",
      optic: "B+",
      colour: { en: "Yellow", si: "කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.020",
      sg: "2.98",
      hardness: "5½",
      dispersion: "0.014",
      dichroism: { en: "Weak", si: "දුර්වලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Pegmatite deposits, Minas Gerais, Brazil", si: "පෙග්මෙටික් නිධිය, මිනාස් ගරයිස් බ්‍රසීලය (Minas Gerais)" },
      discoverer: "",
      comments: { en: "Conchoidal (circular) fracture. Named after Brazil, where it was found.", si: "බිඳීම චක්‍රාකාරය. බ්‍රසීලයේ හමු වූ නිසා මෙම නම තබා ඇත." },
      year: "1945"
    }
  },
  {
    id: "bromellite",
    no: 15,
    swatch: "#EDEDE6",
    name: { en: "Bromellite", si: "බ්‍රොමෙල්ලයිට්" },
    group: "Periclase",
    fields: {
      formula: "BeO",
      composition: "Beryllium Oxide",
      crystal: "Hexagonal",
      group: "Periclase",
      lustre: "Adamantine",
      ri: "1.718 – 1.732",
      optic: "U+",
      colour: { en: "Colourless", si: "අවර්ණ" },
      absorption: "",
      inclusions: { en: "Fine, straight brown fibre-like inclusions. A yellow crystal exists; colourless crystals also occur.", si: "කෙලින් පිහිටා ඇති දුඹුරු සිහින් කෙඳි අන්තර්ගතව ඇත. කහ ස්ඵටිකයක් ඇත. අවර්ණ ස්ඵටික" },
      birefringence: "0.014",
      sg: "3.01",
      hardness: "9",
      dispersion: "",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Långban, Värmland, Sweden; Ural Mountains, Russia; Gilimale, Ratnapura", si: "ලැන්ග්බෑන් වාම්ලැන්ඩ්, ස්වීඩන් උරල් කඳුවැටිය, රුසියාව, ගිලිමලේ, රත්නපුර." },
      discoverer: "Magnus von Bromell (1679–1731), Swedish mineralogist",
      comments: { en: "Perfect cleavage (1010)(0001) good. Only 3 natural cut bromellite stones are known: 0.68, 1.92 and 2.80 ct. Presented by Dunil Palitha Gunasekara, FGA gemmologist.", si: "ක්‍රාත් 0.68, 1.92 සහ 2.80 ලෝකයේ පළමුවැනි කපා ඔප දැමූ ස්වභාවික බ්‍රොමෙල්ලයිට් ගල් 3 මෙය වේ. ඉදිරිපත් කිරීම දුනිල් පාලිත ගුණසේකර. FGA රත්න විද්‍යාඥ" },
      year: "1825"
    }
  },
  {
    id: "brookite",
    no: 16,
    swatch: "#B5451F",
    name: { en: "Brookite", si: "බෲකයිට්" },
    group: "Rutile",
    fields: {
      formula: "TiO2",
      composition: "Titanium Oxide",
      crystal: "Orthorhombic",
      group: "Rutile",
      lustre: "Adamantine",
      ri: "2.58 – 2.74",
      optic: "B+",
      colour: { en: "Brown, Yellow, Red, Black, Blue", si: "දුඹුරු, කහ, රතු, කළු, නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.157",
      sg: "4.14",
      hardness: "6",
      dispersion: "0.131",
      dichroism: { en: "Strong: yellow, red, brown", si: "ප්‍රබලය කහ, රතු, දුඹුරු" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "California and New York (USA), England, France, Brazil", si: "CA, USA, NEWYORK, ENGLAND, FRANCE, BRAZIL" },
      discoverer: "Henry James Brooke (1771–1857), English mineralogist",
      comments: { en: "A rare stone. Polymorphous with rutile and anatase; the chemical formula is the same, TiO2.", si: "දුර්ලභ ගලකි. Polymorphous, Rutile, Anatase. රසායනික සූත්‍රය එකම වේ. TiO2" },
      year: "1825"
    }
  },
  {
    id: "calcite",
    no: 17,
    swatch: "#E8E2CE",
    name: { en: "Calcite", si: "කැල්සයිට්" },
    group: "Calcite",
    fields: {
      formula: "CaCO3",
      composition: "Calcium Carbonate",
      crystal: "Trigonal",
      group: "Calcite",
      lustre: "Vitreous",
      ri: "1.486 – 1.740",
      optic: "U-",
      colour: { en: "Colourless, White, Grey, Yellow", si: "අවර්ණ, සුදු, අළු, කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.190",
      sg: "2.71",
      hardness: "3",
      dispersion: { en: "Strong", si: "ප්‍රබලයි" },
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Calx = lime / Balangoda", si: "Calx = lime / බලංගොඩ" },
      discoverer: "Haidinger",
      comments: { en: "At Balangoda there is a large white calcite hill. Greek/Latin root meaning to reduce to powder by heat (calx = lime).", si: "බලංගොඩ, විශාල සුදු කැල්සයිට් කන්දක් තිබේ" },
      year: "1825"
    }
  },
  {
    id: "cassiterite",
    no: 18,
    swatch: "#7A5A3C",
    name: { en: "Cassiterite", si: "කැසිටියරයිට්" },
    group: "Rutile",
    fields: {
      formula: "SnO2",
      composition: "Tin Oxide",
      crystal: "Tetragonal",
      group: "Rutile",
      lustre: "Adamantine",
      ri: "2.00 – 2.10",
      optic: "U+",
      colour: { en: "Colourless, White, Grey, Yellow, Red", si: "අවර්ණ, සුදු, අළු, කහ, රතු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.098",
      sg: "6.95",
      hardness: "6½",
      dispersion: "0.071",
      dichroism: { en: "Weak", si: "දුර්වලයි" },
      transparency: { en: "Transparent to Opaque", si: "පාරදෘශ්‍ය සහ පාරාන්ධ" },
      locality: { en: "Found together with metamict allanite. Gowuvahela, Badulla.", si: "මෙටමික්ට් ඇලනයිට් සමඟ හමු වී ඇත. ගොවුවාහෙල, බදුල්ල." },
      discoverer: "",
      comments: { en: "A rare gemstone. Greek 'kassiteros' = tin.", si: "දුර්ලභ මැණික් ගලකි." },
      year: "1832"
    }
  },
  {
    id: "celestine",
    no: 19,
    swatch: "#A8CCE6",
    name: { en: "Celestine", si: "සෙලීස්ටයින්" },
    group: "Barite",
    fields: {
      formula: "SrSO4",
      composition: "Strontium Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Vitreous",
      ri: "1.623 – 1.633",
      optic: "B+",
      colour: { en: "Pale blue and colourless", si: "ලා නිල්, සහ අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.010",
      sg: "4.00",
      hardness: "3½",
      dispersion: { en: "Weak", si: "දුර්වලයි" },
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Madagascar", si: "මැඩගස්කරය" },
      discoverer: "",
      comments: { en: "Has 2 cleavages. Shows a white-blue glow under ultraviolet light. Crystals form inside geodes. Latin 'coelestis' – from its pale blue colour.", si: "පැති 2කට පැළුම ඇත. පාරජම්බුල කිරණ තුළ සුදු-නිල් දීප්තිය ඇත. ගෙඩියක් තුල ස්ඵටික පිහිටා ඇත." },
      year: "1791"
    }
  },
  {
    id: "chondrodite",
    no: 20,
    swatch: "#B5502A",
    name: { en: "Chondrodite", si: "කොන්ඩ්‍රොඩයිට්" },
    group: "Humite",
    fields: {
      formula: "Mg(OH,F)2Mg2(SiO4)",
      composition: "Magnesium, Fluorine, Silicate",
      crystal: "Monoclinic",
      group: "Humite",
      lustre: "Adamantine",
      ri: "1.59 – 1.64",
      optic: "B-",
      colour: { en: "Orange, Red", si: "තැඹිලි, රතු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.028 – 0.034",
      sg: "3.23",
      hardness: "6½",
      dispersion: "0.071",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Tilley Foster Mine, NY", si: "Tilley Foster Mine, NY" },
      discoverer: "d'Ohsson",
      comments: { en: "Orange-red chondrodite occurs on the surface of white dolomite rock. Balangoda. Greek 'granule' – in allusion to its occurrence as isolated grains.", si: "ඩොලමයිට් (සුදු) ගල මතුපිට ක්‍රොන්ඩ්‍රොඩයිට් තැඹිලි රතු වර්ණය පිහිටා ඇත. බලංගොඩ." },
      year: "1817"
    }
  },
  {
    id: "chrysoberyl",
    no: 21,
    swatch: "#C7C24A",
    name: { en: "Chrysoberyl", si: "කනක" },
    group: "Chrysoberyl",
    fields: {
      formula: "BeAl2O4",
      composition: "Beryllium, Aluminate",
      crystal: "Orthorhombic",
      group: "Chrysoberyl",
      lustre: "Vitreous",
      ri: "1.746 – 1.756",
      optic: "B+",
      colour: { en: "Green, Yellow, Greenish brown, Alexandrite green; alexandrite shows a red colour in artificial light", si: "කොළ, කහ, කොළ දුඹුරු, පසිංගල් කොළ; Alexandrite කෘතිම ආලෝකය තුල රතු වර්ණය ගෙනදේ" },
      absorption: {
        en: "Chrysoberyl: due to iron, a broad band at 4440 Å. Alexandrite: chromium – strong double at 6805/6875; weak thin lines at 6650, 6550, 6490, 6400–5500.",
        si: "කනක - යකඩ නිසා පලල් තිරුවක් 4440Å ඇත. පසිංගල් - ක්‍රෝමියම් - double - 6805/6875 ප්‍රබලය. දුර්වල හීන් රේඛා 6650, 6550, 6490, 6400 - 5500 ඇත."
      },
      inclusions: "",
      birefringence: "0.009",
      sg: "3.75",
      hardness: "8½",
      dispersion: "0.015",
      dichroism: { en: "Strong. Alexandrite: red / green", si: "ප්‍රබලය පසිංගල් රතු / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Alexandrite occurs with mica deposits – a very valuable gemstone. Ural Mountains (Russia), Madagascar, Sri Lanka, Brazil.", si: "මයිකා නිධි සමග පසිංගල් හමුවේ ඉතා වටිනා මැණික් ගලකි. උරල් කඳු රුසියාව, මැඩගස්කරය, ශ්‍රී ලංකාව, බ්‍රසීලය." },
      discoverer: "",
      comments: { en: "Green-yellow colour (vanadium chrysoberyl). A 475 ct green-yellow cut and polished chrysoberyl has been found (Ravi Gems). Name from Greek 'golden' + 'beryl'; alexandrite named after Tsar Alexander II of Russia (1833).", si: "කොළ කහ වර්ණය (වැනේඩියම් කනක)" },
      year: "1790"
    }
  },
  {
    id: "natural-cobalt-spinel",
    no: 22,
    swatch: "#3C5FC4",
    name: { en: "Natural Cobalt Spinel", si: "ස්වභාවික කොබෝල්ට් කිරිංචි" },
    group: "Spinel",
    fields: {
      formula: "MgAl2O4+Co",
      composition: "Cobalt, Magnesium, Aluminate",
      crystal: "Cubic",
      group: "Spinel",
      lustre: "Vitreous",
      ri: "1.715 / 1.718",
      optic: "B+",
      colour: { en: "Electric blue; colour-change (red) stones also occur", si: "ඉලෙක්ට්‍රික් නිල් වර්ණ වෙනස්වන (රතු) ගල් ද ඇත." },
      absorption: { en: "3 strong lines: 623, 597 (broad); 579, 544, 480 nm (strong line due to iron)", si: "ප්‍රබල රේඛා 3ක් ඇත. 623, 597 (මහත) 579, 544, 480, nm (යකඩ නිසා ප්‍රබල රේඛාවක් ඇත.)" },
      inclusions: { en: "2-phase fluid trails", si: "2 - Phase ද්‍රව තාරායම්" },
      birefringence: "",
      sg: "3.52",
      hardness: "8",
      dispersion: "0.020",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Okkampitiya – a collection of cobalt spinel crystals, weight 2.20 kg (museum, Ratnapura). An identification report was given by the author.", si: "ඔක්කම්පිටිය - කොබෝල්ට් කිරිංචි ස්ඵටික එකතුවක්. බර 2.20Kg මිහිමුසියම්, රත්නපුර. කර්තා විසින් හඳුනාගැනීමේ වාර්තාව දී ඇත." },
      discoverer: "Dr. Dunil Palitha Gunasekara (Gemmologist), 1980",
      comments: { en: "The refractive index of synthetic cobalt spinel is 1.722. The largest cut cobalt spinel, 41.65 ct, was examined by the author – a rare blue gemstone.", si: "කෘතිම කොබෝල්ට් කිරිංචි හි වර්තන අංකය 1.722 කි" },
      year: "1983"
    }
  },
  {
    id: "cordierite-iolite",
    no: 23,
    swatch: "#7A78C8",
    name: { en: "Cordierite – Iolite", si: "කෝඩියරයිට් - අයෝලයිට්" },
    group: "Beryl",
    fields: {
      formula: "(Mg,Fe)2Al4Si5O18",
      composition: "Magnesium, Aluminium, Iron, Silicate",
      crystal: "Orthorhombic",
      group: "Beryl",
      lustre: "Vitreous",
      ri: "1.53 – 1.54",
      optic: "B+",
      colour: { en: "Blue, Violet, Colourless, White", si: "නිල්, දම්, අවර්ණ, සුදු" },
      absorption: { en: "Several lines: 6450, 5930, 5850, 5350, 4920, 4560, 4360, 4260 Å", si: "රේඛා කිපයක් ඇත. 6450, 5930, 5850, 5350, 4920, 4560, 4360, 4260 Å" },
      inclusions: "",
      birefringence: "0.005 – 0.018",
      sg: "2.53 – 2.65",
      hardness: "7",
      dispersion: "0.017",
      dichroism: { en: "Strong, blue / violet", si: "ප්‍රබලය නිල්/ දම්" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Badulla, Sri Lanka.", si: "බදුල්ල, ශ්‍රී ලංකාව." },
      discoverer: "Pierre Louis A. Cordier (1777–1861), French geologist",
      comments: { en: "Single-thread and 6-thread iolite have been found. Iolite: Greek 'ios' (violet) + 'lithos' (stone).", si: "තනි නූල් සහ නූල් 6 අයෝලයිට් හමු වී ඇත." },
      year: "1813"
    }
  },
  {
    id: "corundum",
    no: 24,
    swatch: "#2B4CB8",
    name: { en: "Corundum (Sapphire)", si: "කොරන්ඩම් (සැපයර්)" },
    group: "Corundum – Hematite",
    fields: {
      formula: "Al2O3+Fe,Ti,Cr",
      composition: "Aluminium Oxide + Iron + Titanium, Chromium",
      crystal: "Trigonal (barrel-shaped, dipyramidal, flat tabular)",
      group: "Corundum – Hematite",
      lustre: "Vitreous",
      ri: "1.76 – 1.77",
      optic: "U-",
      colour: {
        en: "Red (ruby), Blue (blue sapphire), Yellow (yellow sapphire), Colourless / White / Blue, Padparadscha (red-yellow mix), Star (6 silver rays), Geuda, Diesel white; heat treatment gives blue colour. Violet, Green, Dark blue, Crow blue.",
        si: "රතු (රූබි) නිල් (Blue Sapphire) රත්නපුෂ්පරාග, පුෂ්පරාග (කහ) අවර්ණ සුදු නිල්, පද්මරාග (Padparadscha) (රතු කහ මිශ්‍ර) ආර්නුල් (රිදී නූල් 6ක් ඇත) ගෙවුඩ, ඩීසල් සුදු පාට, සහ දුම්ගල් පිච්චිමෙන් නිල් වර්ණය ගෙන දෙයි. දම්, කොළ, තද නිල්, කාක නිල"
      },
      absorption: {
        en: "Ruby: strong doublet at 6942/6928; weak lines at 6680, 6592; broad dark absorption in yellow-green. 3 further lines. Blue (iron) / green-blue: 3 lines at 4000, 4600, 4500.",
        si: "රතු කැටයේ ප්‍රබල ඩබ්ලට් 6942/6928 ඇත. දුර්වල රේඛා 6680, 6592 පළල කළු උරාගැනීමක් කහ කොළ හි ඇත. තවද රේඛා 3ක් ඇත. නිල් - අයන් - කොළල නිල් හි රේඛා 3ක් ඇත. 4000, 4600, 4500"
      },
      inclusions: "",
      birefringence: "0.008",
      sg: "3.99 – 4.00",
      hardness: "9",
      dispersion: "0.018",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Corundum crystals occur in marble. Ratnapura district, Elahera, Polonnaruwa, Kataragama, Madagascar, Burma, Africa", si: "මාබල් ගල තුල කොරන්ඩම් ස්ඵටික පිහිටා ඇත. රත්නපුර දිස්ත්‍රික්කය, ඇලහැර, පොලොන්නරුව, කතරගම, මැඩගස්කරය, බුරුමය, අප්‍රිකාව" },
      discoverer: "",
      comments: { en: "Ruby shows red fluorescence under long-wave UV. An 8 ct ruby (Myanmar) was sold for USD 2.2 million. 'Kuruvindam' is the Tamil name for ruby.", si: "පාරජම්බුල කිරණ (LWUV) තුල රතු කැට ප්‍රදීපනයක් පෙන්නුම් කරයි. ක්‍රාත් 8 ක රතු කැටයක් (මියන්මාරය) ඇ. ඩොලර් මිලියන 2.2 විකිණී ඇත. රතු Ruby \"කුරුවින්දම්\" දෙමළ නමකි." },
      year: ""
    }
  },
  {
    id: "danburite",
    no: 25,
    swatch: "#E9DDB8",
    name: { en: "Danburite", si: "ඩැන්බුරයිට්" },
    group: "Lamprophyllite",
    fields: {
      formula: "CaB2Si2O8",
      composition: "Calcium, Boron, Silicate",
      crystal: "Orthorhombic (crystals with sharp edges)",
      group: "Lamprophyllite",
      lustre: "Vitreous",
      ri: "1.630 – 1.636",
      optic: "B-",
      colour: { en: "Colourless, Yellow, Pink, Grey, White, Brown", si: "අවර්ණ, කහ, රෝස, අළු, සුදු, දුඹුරු" },
      absorption: { en: "Rare earth – didymium lines", si: "රෙයා එර්ත් - ඩිමියම් රේඛා ඇත." },
      inclusions: "",
      birefringence: { en: "Weak", si: "දුර්වලය" },
      sg: "3.00",
      hardness: "7",
      dispersion: "0.017",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found on dolomite rock (Danbury, Connecticut, USA). Burma, Madagascar. Ratnapura district, Polonnaruwa, Bogawantalawa, Kolonna.", si: "ඩොලමයිට් ගල (Danbury, Connectical, USA) මතුපිට හමුවේ. බුරුමය, මැඩගස්කරය. රත්නපුර දිස්ත්‍රික්කය, පොළොන්නරුව, බගවන්තලාව, කොලොන්න" },
      discoverer: "C. U. Shepard",
      comments: { en: "Can be distinguished from similar-looking stones by specific gravity and refractive indices.", si: "පඩියං ගලෙන් වෙන්කර ගත හැකේ වි.ගු. සහ වර්තන අංක වලිනි." },
      year: "1939"
    }
  },
  {
    id: "demantoid-garnet",
    no: 26,
    swatch: "#3FA83A",
    name: { en: "Demantoid Garnet", si: "ඩිමැන්ටොයිඩ් රබහ" },
    group: "Garnet",
    fields: {
      formula: "Ca3Fe2(SiO4)3",
      composition: "Calcium, Iron, Silicate",
      crystal: "Cubic (octahedral, dodecahedral crystals)",
      group: "Garnet (Andradite)",
      lustre: "Adamantine",
      ri: "1.888",
      optic: "",
      colour: { en: "Green", si: "කොළ" },
      absorption: { en: "A strong band at 4430 Å", si: "4430Å හි තද ප්‍රබල රේඛාවක් ඇත." },
      inclusions: { en: "Horse-tail inclusions", si: "Horse - Rail අන්තර්ගතය ඇත." },
      birefringence: "",
      sg: "3.82 – 3.88",
      hardness: "6",
      dispersion: "0.057",
      dichroism: "",
      transparency: { en: "Transparent; high dispersion gives it a high lustre (fire)", si: "පාරදෘශ්‍ය, අපකිරණය වැඩි නිසා අභි ප්‍රභවය ඇත." },
      locality: { en: "Ural Mountains (Russia), Madagascar. Crystals occur on serpentine rock.", si: "උරල් කඳු - රුසියාව, මැඩගස්කරය, සර්පන්ටින් ගල මතුපිට ස්ඵටික සැදි ඇත." },
      discoverer: "V.B.D. Andrada e Silva (1763–1838), Brazilian mineralogist",
      comments: { en: "A fairly expensive gemstone. Green colour is due to chromium. Through a colour filter it appears dark reddish. A rare gemstone. Some stones show anomalous double refraction.", si: "තුඩිය වැඩි මැණික් ගලකි. කොළ වර්ණයක්‍රෝමියම් නිසා සිදු වී ඇත. වෙල්සි පෙරණයෙන් බැලුවිට තද රතු පැහැයට පෙනේ. දුර්ලභ මැණික් ගලකි. සමහර ගල් වල ඇනමෝලස් ද්වි වර්තනයක් පෙන්නුම් කරයි." },
      year: "1868"
    }
  },
  {
    id: "diamond",
    no: 27,
    swatch: "#DCEBF2",
    name: { en: "Diamond", si: "දියමන්ති" },
    group: "",
    fields: {
      formula: "C",
      composition: "Carbon",
      crystal: "Cubic (octahedral, dodecahedral crystals)",
      group: "",
      lustre: "Adamantine",
      ri: "2.418",
      optic: "",
      colour: { en: "Colourless, Yellow, Brown, Pink, Green, Orange, Blue, Dark red", si: "අවර්ණ, කහ, දුඹුරු, රෝස, කොළ, තැඹිලි, නිල්, තද රතු." },
      absorption: { en: "4155, 4785, 4650, 4520, 4350, 4230", si: "4155, 4785, 4650, 4520, 4350, 4230" },
      inclusions: { en: "Crystal / garnet inclusions present", si: "ස්ඵටික රබහ ඇත." },
      birefringence: "",
      sg: "3.52",
      hardness: "10",
      dispersion: "0.044",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Balibathgoda, Muwagama, Ratnapura – a 6.02 ct octahedral, pale yellow-brown diamond was found. Africa, India, Brazil, Russia.", si: "බලිබත්ගොඩ, මුවගම, රත්නපුර, ක්‍රාත් 6.02 ක අෂ්ඨතල, ලා කහ-දුඹුරු දියමන්ති ස්ඵටිකයක් හමු වී ඇත. අප්‍රිකාව, ඉන්දියාව, බ්‍රසීලය, රුසියාව." },
      discoverer: "",
      comments: {
        en: "The hardest gemstone (10 on the Mohs scale). Has cleavage in one direction: a stone can be split along octahedral planes, which is useful in cutting. An 8 ct polished colourless diamond sold for Rs. 7 crore. A 777 ct rough diamond took 3 years to cut and polish.",
        si: "පැල්ම එක් පැත්තකට ඇත. ඔක්ටාහෙඩ්‍රල් තල අනුව ලේසියෙන් ගල දෙකඩ කළ හැක. කැපීමේ දී එය ප්‍රයෝජනවත් වේ. ක්‍රාත් 8 ක ඔප දැමූ අවර්ණ දියමන්තියක්, රු. කෝටි 7 විකුණා ඇත. ක්‍රාත් 777 අමු දියමන්ති ගලක් කපා ඔප දැමීම සඳහා අවුරුදු 3ක් ගත වී ඇත."
      },
      year: "1868"
    }
  },
  {
    id: "diaspore",
    no: 28,
    swatch: "#C9C79A",
    name: { en: "Diaspore", si: "ඩයස්පෝරි" },
    group: "Diaspore",
    fields: {
      formula: "AlO(OH)+Mn",
      composition: "Aluminium, Manganese Hydroxide Oxide",
      crystal: "Orthorhombic",
      group: "Diaspore",
      lustre: "Vitreous",
      ri: "1.702 – 1.750",
      optic: "B+",
      colour: { en: "Colourless, White, Yellow, Pink, Greenish Brown", si: "අවර්ණ, සුදු, කහ, රෝස, කොළ දුඹුරු (Greenish Brown)" },
      absorption: { en: "3 broad lines: 4710, 4630, 4540 Å", si: "පළල රේඛා 03ක් ඇත. 4710, 4630, 4540Å." },
      inclusions: "",
      birefringence: "0.048",
      sg: "3.39",
      hardness: "7",
      dispersion: "",
      dichroism: { en: "Strong: violet-blue, pale green, pink", si: "ප්‍රබලය, දම් නිල් ලා කොළ, රෝස" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Anatolia, Turkey 1977; Ural, Russia.", si: "Anatolia, Turkey 1977, Ural.Russia." },
      discoverer: "",
      comments: { en: "A foreign stone. A very rare gemstone. Greek 'dias' – to scatter, for its unusual decrepitation before the blowpipe.", si: "පිටරට ගලකි. අති දුර්ලභ මැණික් ගලකි." },
      year: "1801"
    }
  },
  {
    id: "diopside",
    no: 29,
    swatch: "#2E7D32",
    name: { en: "Diopside", si: "ඩයොප්සයිඩ්" },
    group: "Pyroxene",
    fields: {
      formula: "CaMgSi2O6",
      composition: "Calcium, Magnesium, Silicate",
      crystal: "Monoclinic (four-sided prismatic crystals)",
      group: "Pyroxene",
      lustre: "Vitreous",
      ri: "1.670 – 1.700",
      optic: "B+",
      colour: { en: "Green, Yellow, Black, Pale green", si: "කොළ, කහ, කළු, ලා කොළ" },
      absorption: { en: "Chrome-diopside: 2 sharp lines at 508, 505 nm", si: "Chrome - Diopside 2 sharp lines at 508, 505 nm." },
      inclusions: { en: "Horse-tail inclusions", si: "Horse - Rail අන්තර්ගතය ඇත." },
      birefringence: "0.030",
      sg: "3.29",
      hardness: "7",
      dispersion: "",
      dichroism: { en: "Strong: yellow, green", si: "ප්‍රබලය, කහ, කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Pale green diopside varieties; found at Okkampitiya.", si: "ලා කොළ ඩයොප්සයිඩ් වෛරෝඩි, ඔක්කම්පිටියෙන් හමු වී ඇත." },
      discoverer: "d'Andrada",
      comments: { en: "Greek 'double' + 'appearance'.", si: "Greek - double & appearence" },
      year: "1800"
    }
  }
];

