/* =========================================================
   RathnaHub – data.js
   1) FIELD_DEFS : the 20 rows shown on every gem sheet
                   (same order as the book page).
   2) GEMS       : one object per gem. Add all 105 here.

   A value can be:
     "text"                         -> same in both languages
     { en: "text", si: "සිංහල" }     -> bilingual value
     ""  (or missing)               -> shown as "—"
   ========================================================= */

const FIELD_DEFS = [
  { key: "formula",      en: "Formula",              si: "රසායනික සූත්‍රය" },
  { key: "composition",  en: "Chemical Composition", si: "රසායනික සංයුතිය" },
  { key: "crystal",      en: "Crystal System",       si: "ස්ඵටික පද්ධතිය" },
  { key: "group",        en: "Group",                si: "කාණ්ඩය" },
  { key: "lustre",       en: "Lustre",               si: "දීප්තිය" },
  { key: "ri",           en: "Refractive Indices",   si: "වර්තනාංක" },
  { key: "optic",        en: "Optical Sign",         si: "දෘෂ්ටික ලකුණ" },
  { key: "colour",       en: "Colour",               si: "වර්ණය" },
  { key: "absorption",   en: "Absorption Spectrum",  si: "අවශෝෂණ වර්ණාවලිය" },
  { key: "inclusions",   en: "Inclusions",           si: "අන්තර්ගත" },
  { key: "birefringence",en: "Birefringence",        si: "ද්විවර්තනය" },
  { key: "sg",           en: "Specific Gravity",     si: "විශිෂ්ට ගුරුත්වය" },
  { key: "hardness",     en: "Hardness",             si: "දෘඪතාව" },
  { key: "dispersion",   en: "Dispersion",           si: "වර්ණ ව්‍යාප්තිය" },
  { key: "dichroism",    en: "Dichroism",            si: "ද්වීවර්ණතාව" },
  { key: "transparency", en: "Transparency",         si: "පාරදෘශ්‍යතාව" },
  { key: "locality",     en: "Locality Occurrence",  si: "ඇතිවන ස්ථාන" },
  { key: "discoverer",   en: "Discoverer",           si: "සොයාගත් අය" },
  { key: "comments",     en: "Comments",             si: "අමතර තොරතුරු" },
  { key: "year",         en: "Discovered Year",      si: "සොයාගත් වර්ෂය" }
];

/* "swatch" = a hex colour used to tint the gem icon and card.
   "no"     = the number printed in the book (01, 02, ...). */
const GEMS = [
    {
    id: "actinolite",
    no: 1,
    swatch: "#5E8C6A",
    name: { en: "Actinolite", si: "ඇක්ටිනෝලයිට්" },
    group: "Amphibole",
    fields: {
      formula: "Ca2(Mg,Fe)5(OH)2(Si4O11)2",
      composition: "Calcium, Magnesium, Iron Silicate",
      crystal: "Monoclinic",
      group: "Amphibole",
      lustre: "Vitreous",
      ri: "1.620 – 1.642",
      optic: "B-",
      colour: { en: "Light & Dark Green – Brown", si: "ලා සහ තද කොළ – දුඹුරු" },
      absorption: { en: "A weak line at 503 nm", si: "දුර්වල රේඛාවක් 503nm හි ඇත." },
      inclusions: { en: "Fibre-like inclusions; solid and liquid inclusions", si: "කෙඳි මෙන් අන්තර්ගත, ඝන ද්‍රව තාරායම්" },
      birefringence: "0.022",
      sg: "3.05",
      hardness: "5½",
      dispersion: "",
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Actinolite crystals occur on dolomite rock together with biotite mica. Balangoda, Tanzania", si: "ඩොලමයිට් ගල මතුපිට, බයෝටයිට් මයිකා සමඟ ඇක්ටිනෝලයිට් ස්ඵටික පිහිටා ඇත. බලංගොඩ. ටැන්සානියාව" },
      discoverer: "Richard Kirwan",
      comments: { en: "aktis = ray. Tends to split off in flakes; single-thread (fibrous) forms also occur.", si: "aktis = ray. පතුරු ගැලවෙන ගතිය ඇත. තනි නූල වෛරෝඩි ද ඇත" },
      year: "1794"
    }
  },
  {
    id: "almandine-garnet",
    no: 2,
    swatch: "#8B1A2B",
    name: { en: "Almandine Garnet", si: "ඇල්මන්ඩීන් රබහ" },
    group: "Garnet",
    fields: {
      formula: "Fe3Al2(SiO4)3",
      composition: "Iron, Aluminium, Silicate",
      crystal: "Cubic",
      group: "Garnet",
      lustre: "Vitreous",
      ri: "1.76 – 1.82",
      optic: "",
      colour: { en: "Blood Red", si: "තද රතු" },
      absorption: { en: "3 strong bands: 576, 526, 505 nm", si: "ප්‍රබල රේඛා 3 ඇත. 576, 526, 505 nm" },
      inclusions: "",
      birefringence: "",
      sg: "3.8 – 4.2",
      hardness: "7½",
      dispersion: "0.027",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Alabanda, Turkey / Elahera, Sri Lanka / Madagascar / Africa", si: "Alabanda, Turkey / Elahera, Sri Lanka / Madagaskar / Africa" },
      discoverer: "Agricola 1546 & Karsten",
      comments: { en: "Garnet; star and single-thread varieties also occur", si: "රබහ, ආනුල් සහ තනි නූල වෛරෝඩි ද ඇත" },
      year: "1794"
    }
  },
  {
    id: "amblygonite",
    no: 3,
    swatch: "#D9C84A",
    name: { en: "Amblygonite", si: "ඇම්බ්ලිගෝනයිට්" },
    group: "Tilasite",
    fields: {
      formula: "LiAl(PO4)F",
      composition: "Lithium, Aluminium, Fluorine, Phosphate",
      crystal: "Triclinic",
      group: "Tilasite",
      lustre: "Vitreous",
      ri: "1.611 – 1.637",
      optic: "B+",
      colour: { en: "Colourless, Yellow, Pink", si: "අවර්ණ, කහ, රෝස" },
      absorption: "",
      inclusions: "",
      birefringence: "0.026",
      sg: "3.01",
      hardness: "6",
      dispersion: { en: "Sharp", si: "තියුණුයි" },
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found inside hard rock. Balangoda / Brazil, France, Namibia", si: "කළුගල් ඇතුලත. බලංගොඩ./ බ්‍රසීලය, ප්‍රංශය, නැම්බියාව" },
      discoverer: "",
      comments: { en: "A rare gemstone. Greek name amblygonite ('blunt angle', from the crystal shape). Yellow crystal, 254 ct.", si: "දුර්ලභ මැණික් ගලකි. ස්ඵටික ස්වරූපය, මුවාත නැති, කෝණ ඇත. ග්‍රීක් නම ඇම්බ්ලිගෝනයිට්. ස්ඵටිකය කහ, 254 ක්‍රාත්." },
      year: "1817"
    }
  },
  {
    id: "andalusite",
    no: 4,
    swatch: "#7A8B3A",
    name: { en: "Andalusite", si: "ඇන්ඩලුසයිට්" },
    group: "Andalusite",
    fields: {
      formula: "Al2SiO5",
      composition: "Aluminium, Silicate",
      crystal: "Orthorhombic",
      group: "Andalusite",
      lustre: "",
      ri: "1.634 – 1.641 / 1.644 – 1.648",
      optic: "B-",
      colour: { en: "Green mixed with pink", si: "කොළ මිශ්‍ර රෝස" },
      absorption: { en: "Sharp lines at 5505, 5475 Å, 5535 Å", si: "තියුණු රේඛාවල් ඇත 5505, 5475Å, 5535Å" },
      inclusions: "",
      birefringence: "0.007 – 0.011",
      sg: "3.17",
      hardness: "7½",
      dispersion: "0.016",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රබලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Andalusia province, Spain. Nawalapitiya, Ginigathhena (Sri Lanka), Madagascar.", si: "ඇඩුලූසියා ප්‍රාන්තය, Spain. නාවලපිටිය, ගිනිගත්හේන ශ්‍රී ලංකාව, මැඩගස්කරය." },
      discoverer: "",
      comments: { en: "Polymorphous with sillimanite and kyanite, all sharing the formula Al2SiO5. A rare gemstone; some people are fooled into calling it alexandrite.", si: "Polymorphous පොලිමෝෆස්-සිලිමනයිට් සහ කයනයිට් එම සූත්‍රය ඇත Al2SiO5. ගිනිබොකුතෝර ගැම්නම. දුර්ලභ මැණික් ගලකි.සමහර අය පසිංගලයක් කියා රැවටෙති." },
      year: "1789"
    }
  },
  {
    id: "anglesite",
    no: 5,
    swatch: "#E0A040",
    name: { en: "Anglesite", si: "ඇන්ග්ලිසයිට්" },
    group: "Barite",
    fields: {
      formula: "PbSO4",
      composition: "Lead Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Adamantine",
      ri: "1.877 – 1.894",
      optic: "B+",
      colour: { en: "Colourless, Yellow, Green, Orange, Blue", si: "අවර්ණ, කහ, කොළ, තැඹිලි, නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.017",
      sg: "6.38",
      hardness: "3",
      dispersion: "0.044",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රහලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "In Wales at Parys Mine – Island of Anglesey", si: "In Wales at Parys Mine – Island of Anglesey" },
      discoverer: "",
      comments: { en: "A foreign (imported) stone.", si: "පිටරට ගලකි." },
      year: "1832"
    }
  },
  {
    id: "apatite",
    no: 6,
    swatch: "#2FB5A0",
    name: { en: "Apatite", si: "ඇපටයිට්" },
    group: "Apatite",
    fields: {
      formula: "Ca(F,Cl)Ca4(PO4)",
      composition: "Calcium, Fluorine Phosphate",
      crystal: "Hexagonal",
      group: "Apatite",
      lustre: "Vitreous",
      ri: "1.63 – 1.64",
      optic: "U-",
      colour: { en: "White, Yellow, Green, Blue, Violet, Brown", si: "සුදු, කහ, කොළ, නිල්, දම්, දුඹුරු" },
      absorption: { en: "7 lines at 5800 Å; 5 lines at 5200 Å (didymium). Blue apatite: 5120, 4910, 4640 Å", si: "රේඛා 7ක් 5800Å හි ඇත. රේඛා 5ක් 5200Å හි ඇත. (ඩිඩිමියම්) නිල් ඇපටයිට් - 5120, 4910, 4640Å" },
      inclusions: "",
      birefringence: "0.002 – 0.004",
      sg: "3.18",
      hardness: "5",
      dispersion: "0.013",
      dichroism: { en: "Strong, pink / green", si: "ප්‍රබලය රෝස / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Blue apatite crystals occur within white calcite rock. Balangoda, Madagascar.", si: "සුදු කැල්සයිට් ගල තුල නිල් ඇපටයිට ස්ඵටික පිහිටා ඇත. බලංගොඩ. මැඩගස්කරය." },
      discoverer: "",
      comments: { en: "Apatite varieties also occur. Greek 'apatao' = to deceive: it is easily mistaken for other gems (e.g. aquamarine/beryl).", si: "ඇපටයිට් වෛරෝඩි ඇත. ග්‍රීක් deceive රැවටෙනවා ඇකමරින් (බෙරිල්)" },
      year: "1788"
    }
  },
  {
    id: "azurite",
    no: 7,
    swatch: "#2B4FB0",
    name: { en: "Azurite", si: "ඇසුරයිට්" },
    group: "Halogen",
    fields: {
      formula: "Cu3(OH)2(CO)2",
      composition: "Copper Carbonate",
      crystal: "Monoclinic",
      group: "Halogen",
      lustre: "Vitreous",
      ri: "1.73 – 1.84",
      optic: "B+",
      colour: { en: "Azure Blue", si: "ඇසුරු නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.110",
      sg: "3.77 – 3.88",
      hardness: "4",
      dispersion: "",
      dichroism: "",
      transparency: { en: "Opaque", si: "පාරාන්ධ" },
      locality: { en: "Found within copper deposits in Australia, Mexico, France and Arizona.", si: "ඕස්ට්‍රේලියාව, මෙක්සිකෝ, ප්‍රංශය, ඇරිසෝනා කොපර් නිධි තුළ හමුවේ ඇත." },
      discoverer: "",
      comments: { en: "A foreign gemstone. Has cleavage in one direction. Persian lazhward = blue colour.", si: "පිටරට මැණික් ගලකි. එක් පැත්තකට පැලුම ඇත. Persian lazhward, blue colour තේරුම නිල් වර්ණය" },
      year: "Ancient times"
    }
  },
  {
    id: "baddeleyite",
    no: 8,
    swatch: "#3A3A34",
    name: { en: "Baddeleyite", si: "බැඩ්ලියිට්" },
    group: "Rutile",
    fields: {
      formula: "ZrO2",
      composition: "Zirconium Oxide",
      crystal: "Monoclinic",
      group: "Rutile",
      lustre: "Vitreous – Greasy",
      ri: "2.136 – 2.243",
      optic: "B-",
      colour: { en: "Black, Red, Yellow, Green, Colourless", si: "කළු, රතු, කහ, කොළ, අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.107",
      sg: "5.82",
      hardness: "6½",
      dispersion: "",
      dichroism: { en: "Strong: dark brown / brown / light brown", si: "ප්‍රබලය තද දුඹුරු / දුඹුරු / ලා දුඹුරු" },
      transparency: { en: "Opaque", si: "පාරාන්ධ" },
      locality: { en: "Rakwana, Balangoda. Identified and reported from Sri Lanka. Mt. Somma, Italy.", si: "රක්වාන, බලංගොඩ. ශ්‍රී ලංකාවෙන් සොයා ඉදිරිපත් කර ඇත. සෝමා කන්ද, ඉතාලිය." },
      discoverer: "Joseph Baddeley",
      comments: { en: "Has cleavage. A very rare gemstone. Streak colour: brownish grey.", si: "පැලුම ඇත. අති දුර්ලභ මැණික් ගලකි. කුඩු වර්ණය : දුඹුරු අළු" },
      year: "1892"
    }
  },
  {
    id: "barite",
    no: 9,
    swatch: "#D6B25A",
    name: { en: "Barite", si: "බේරයිට්" },
    group: "Barite",
    fields: {
      formula: "BaSO4",
      composition: "Barium Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Vitreous",
      ri: "1.636 – 1.648",
      optic: "B+",
      colour: { en: "Yellow, Green, Red, Blue, Brown, White", si: "කහ, කොළ, රතු, නිල්, දුඹුරු, සුදු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.012",
      sg: "4.47",
      hardness: "3",
      dispersion: "0.016",
      dichroism: { en: "Weak", si: "දුර්වලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: "",
      discoverer: "",
      comments: { en: "Shows a pale green-blue fluorescence under ultraviolet light. Greek 'baros' = heavy spar; a heavy gemstone.", si: "පාරජම්බුල කිරණ තුළ ලා කොළ නිල් ප්‍රදීපනයක් පෙන්නුම් කරයි. Greek Baros heavy Spar" },
      year: "1640"
    }
  },
  {
    id: "benitoite",
    no: 10,
    swatch: "#2F4FBF",
    name: { en: "Benitoite", si: "බෙනිටොයිට්" },
    group: "Benitoite",
    fields: {
      formula: "BaTiSi3O9",
      composition: "Barium Titanium Silicate",
      crystal: "Hexagonal",
      group: "Benitoite",
      lustre: "Vitreous",
      ri: "1.757 – 1.804",
      optic: "U-",
      colour: { en: "Sapphire blue, Colourless", si: "සපයර් නිල් වර්ණය, අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.047",
      sg: "3.64",
      hardness: "6½",
      dispersion: "0.047",
      dichroism: { en: "Strong, blue / violet", si: "ප්‍රබලය නිල් / දම්" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found within igneous rock. San Benito River, California, USA", si: "ආග්නේය පාෂාණය තුළ පිහිටයි. San Benito river, Califonia, USA" },
      discoverer: "",
      comments: { en: "Named after the place where it was found. A foreign stone; shows strong blue fluorescence under short-wave ultraviolet light. A rare gemstone.", si: "හමුවුනු ස්ථානයේ නම යොදා ඇත. පිටරට ගලකි. කෙටි තරංග පාරජම්බුල කිරණ තුළ ප්‍රබල නිල් ප්‍රදීපයකින් පෙන්නුම් කරයි. දුර්ලභ මැණික් ගලකි." },
      year: "1907"
    }
  },
  {
    id: "beryl",
    no: 11,
    swatch: "#4CB58A",
    name: { en: "Beryl", si: "බෙරිල්" },
    group: "Beryl",
    fields: {
      formula: "Be3Al2(SiO3)6",
      composition: "Beryllium, Aluminium, Silicate",
      crystal: "Hexagonal",
      group: "Beryl",
      lustre: "Vitreous",
      ri: "1.57 – 1.58",
      optic: "U-",
      colour: {
        en: "Emerald – Grass Green; Aquamarine – Bluish Green; Morganite – Pink; Goshenite – Colourless; Heliodor – Yellow",
        si: "මරකත - තණකොළ පාට; ඇකමරින් (නිල් තරප්පු) - නිල් මිශ්‍ර කොළ, මුහුදු වතුර පාට; මෝගනයිට් - රෝස පාට; ගොෂෙනයිට් - අවර්ණ; හෙලියඩෝ - කහ"
      },
      absorption: { en: "Emerald: 2 strong lines (doublet) at 680 and 637 nm; also a line at 477 nm.", si: "එමරල්ඩ් ප්‍රබල රේඛා 2 ඇත. (doublet) 680 සහ 637. තින් රේඛාවක් 477 nm හි ඇත." },
      inclusions: { en: "3-phase inclusions in emerald", si: "3 phase inclusions in Emerald" },
      birefringence: "0.006",
      sg: "2.70",
      hardness: "7½",
      dispersion: "",
      dichroism: { en: "Strong", si: "ප්‍රබලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Aquamarine occurs in pegmatite crystals. Ratnapura, Madagascar, Brazil.", si: "ඇකමරින් - පළිඟු ස්ඵටික තුළ පිහිටා ඇත. රත්නපුර, මැඩගස්කරය, බ්‍රසීලය." },
      discoverer: "",
      comments: { en: "Shows a pale green-blue fluorescence under ultraviolet light. Name from Greek 'beryllos'.", si: "පාරජම්බුල කිරණ තුළ ලා කොළ නිල් ප්‍රදීපනයක් පෙන්නුම් කරයි. බෙරිලෝස්" },
      year: "Ancient times"
    }
  },
  {
    id: "beryllonite",
    no: 12,
    swatch: "#E4DDA0",
    name: { en: "Beryllonite", si: "බෙරිලෝනයිට්" },
    group: "Phosphate",
    fields: {
      formula: "NaBePO4",
      composition: "Beryllium, Sodium, Phosphate",
      crystal: "Monoclinic",
      group: "Phosphate",
      lustre: "Vitreous",
      ri: "1.553 – 1.562",
      optic: "B-",
      colour: { en: "Colourless, White, Pale Yellow", si: "අවර්ණ, සුදු, ලා කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.009",
      sg: "2.85",
      hardness: "5",
      dispersion: "0.010",
      dichroism: { en: "None", si: "නැත" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Stoneham, Maine, USA – in hard-rock cavities", si: "Stoneham, Main, USA කළුගල් කුහර තුළ" },
      discoverer: "",
      comments: { en: "A foreign stone. No colour change under ultraviolet light. A rare gemstone. Named for its beryllium content.", si: "පිටරට ගලකි. පාරජම්බුල කිරණ තුළ වර්ණවත් වෙනසක් නොමැත. දුර්ලභ මැණික් ගලකි. බෙරිලියම් සූත්‍රයේ ඇති නිසා නම දී ඇත." },
      year: "1888"
    }
  },
  {
    id: "bonnynite",
    no: 13,
    swatch: "#2E9C84",
    name: { en: "Bonnynite", si: "බොනීනයිට්" },
    group: "Aenigmatite",
    fields: {
      formula: "(Ca,Na)2(Al,Mg,Fe2+,Fe3+)6(Si,B,Al)6O20",
      composition: "Calcium, Sodium, Aluminium, Magnesium, Iron, Boron Oxide",
      crystal: "Triclinic",
      group: "Aenigmatite",
      lustre: "Vitreous",
      ri: "α 1.697, β 1.700, γ 1.702",
      optic: "B-",
      colour: { en: "Bluish Green", si: "නිල මිශ්‍ර කොළ" },
      absorption: { en: "One strong line at 470", si: "එක් ප්‍රබල රේඛාවක් 470 හි ඇත." },
      inclusions: { en: "White marked crystals, 2 parallel lines. Polysynthetic twinned", si: "සුදු සළකුණු ස්ඵටික, සමාන්තර ඉරි 2. Polysynthetic Twinned" },
      birefringence: "0.005",
      sg: "3.44",
      hardness: "7",
      dispersion: "0.025",
      dichroism: { en: "Strong: yellow, blue, green", si: "ප්‍රබලය / කහ, නිල්, කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Ginigalgoda, Kolonna, Sri Lanka", si: "ගිනිගල්ගොඩ, කොලොන්න, ශ්‍රී ලංකාව" },
      discoverer: "Dr. Dunil Palitha Gunasekara (Gemmologist)",
      comments: { en: "A new gemstone. Named after his mother's first name, Bonny. The name Bonnynite was approved by D.G. Minatidis, a scientist from Greece. Named in 2000.", si: "අළුත් මැණික් ගලකි. කතෘ ගේ මවගේ මුල් නම බොනි. ග්‍රීසියේ D.G. Minatidis නම් විද්‍යාඥයා විසින් බොනීනයිට් නම අනුමත කර ඇත." },
      year: "1996"
    }
  },
  {
    id: "brazilianite",
    no: 14,
    swatch: "#B9C243",
    name: { en: "Brazilianite", si: "බ්‍රසීල්නයිට්" },
    group: "Vilasite",
    fields: {
      formula: "NaAl3(PO4)2(OH)4",
      composition: "Hydrous Sodium, Aluminium, Phosphate",
      crystal: "Monoclinic",
      group: "Vilasite",
      lustre: "Vitreous",
      ri: "1.603 – 1.623",
      optic: "B+",
      colour: { en: "Yellow", si: "කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.020",
      sg: "2.98",
      hardness: "5½",
      dispersion: "0.014",
      dichroism: { en: "Weak", si: "දුර්වලය" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Pegmatite deposits, Minas Gerais, Brazil", si: "පෙග්මෙටික් නිධිය, මිනාස් ගරයිස් බ්‍රසීලය (Minas Gerais)" },
      discoverer: "",
      comments: { en: "Conchoidal (circular) fracture. Named after Brazil, where it was found.", si: "බිඳීම චක්‍රාකාරය. බ්‍රසීලයේ හමු වූ නිසා මෙම නම තබා ඇත." },
      year: "1945"
    }
  },
  {
    id: "bromellite",
    no: 15,
    swatch: "#EDEDE6",
    name: { en: "Bromellite", si: "බ්‍රොමෙල්ලයිට්" },
    group: "Periclase",
    fields: {
      formula: "BeO",
      composition: "Beryllium Oxide",
      crystal: "Hexagonal",
      group: "Periclase",
      lustre: "Adamantine",
      ri: "1.718 – 1.732",
      optic: "U+",
      colour: { en: "Colourless", si: "අවර්ණ" },
      absorption: "",
      inclusions: { en: "Fine, straight brown fibre-like inclusions. A yellow crystal exists; colourless crystals also occur.", si: "කෙලින් පිහිටා ඇති දුඹුරු සිහින් කෙඳි අන්තර්ගතව ඇත. කහ ස්ඵටිකයක් ඇත. අවර්ණ ස්ඵටික" },
      birefringence: "0.014",
      sg: "3.01",
      hardness: "9",
      dispersion: "",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Långban, Värmland, Sweden; Ural Mountains, Russia; Gilimale, Ratnapura", si: "ලැන්ග්බෑන් වාම්ලැන්ඩ්, ස්වීඩන් උරල් කඳුවැටිය, රුසියාව, ගිලිමලේ, රත්නපුර." },
      discoverer: "Magnus von Bromell (1679–1731), Swedish mineralogist",
      comments: { en: "Perfect cleavage (1010)(0001) good. Only 3 natural cut bromellite stones are known: 0.68, 1.92 and 2.80 ct. Presented by Dunil Palitha Gunasekara, FGA gemmologist.", si: "ක්‍රාත් 0.68, 1.92 සහ 2.80 ලෝකයේ පළමුවැනි කපා ඔප දැමූ ස්වභාවික බ්‍රොමෙල්ලයිට් ගල් 3 මෙය වේ. ඉදිරිපත් කිරීම දුනිල් පාලිත ගුණසේකර. FGA රත්න විද්‍යාඥ" },
      year: "1825"
    }
  },
  {
    id: "brookite",
    no: 16,
    swatch: "#B5451F",
    name: { en: "Brookite", si: "බෲකයිට්" },
    group: "Rutile",
    fields: {
      formula: "TiO2",
      composition: "Titanium Oxide",
      crystal: "Orthorhombic",
      group: "Rutile",
      lustre: "Adamantine",
      ri: "2.58 – 2.74",
      optic: "B+",
      colour: { en: "Brown, Yellow, Red, Black, Blue", si: "දුඹුරු, කහ, රතු, කළු, නිල්" },
      absorption: "",
      inclusions: "",
      birefringence: "0.157",
      sg: "4.14",
      hardness: "6",
      dispersion: "0.131",
      dichroism: { en: "Strong: yellow, red, brown", si: "ප්‍රබලය කහ, රතු, දුඹුරු" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "California and New York (USA), England, France, Brazil", si: "CA, USA, NEWYORK, ENGLAND, FRANCE, BRAZIL" },
      discoverer: "Henry James Brooke (1771–1857), English mineralogist",
      comments: { en: "A rare stone. Polymorphous with rutile and anatase; the chemical formula is the same, TiO2.", si: "දුර්ලභ ගලකි. Polymorphous, Rutile, Anatase. රසායනික සූත්‍රය එකම වේ. TiO2" },
      year: "1825"
    }
  },
  {
    id: "calcite",
    no: 17,
    swatch: "#E8E2CE",
    name: { en: "Calcite", si: "කැල්සයිට්" },
    group: "Calcite",
    fields: {
      formula: "CaCO3",
      composition: "Calcium Carbonate",
      crystal: "Trigonal",
      group: "Calcite",
      lustre: "Vitreous",
      ri: "1.486 – 1.740",
      optic: "U-",
      colour: { en: "Colourless, White, Grey, Yellow", si: "අවර්ණ, සුදු, අළු, කහ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.190",
      sg: "2.71",
      hardness: "3",
      dispersion: { en: "Strong", si: "ප්‍රබලයි" },
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Calx = lime / Balangoda", si: "Calx = lime / බලංගොඩ" },
      discoverer: "Haidinger",
      comments: { en: "At Balangoda there is a large white calcite hill. Greek/Latin root meaning to reduce to powder by heat (calx = lime).", si: "බලංගොඩ, විශාල සුදු කැල්සයිට් කන්දක් තිබේ" },
      year: "1825"
    }
  },
  {
    id: "cassiterite",
    no: 18,
    swatch: "#7A5A3C",
    name: { en: "Cassiterite", si: "කැසිටියරයිට්" },
    group: "Rutile",
    fields: {
      formula: "SnO2",
      composition: "Tin Oxide",
      crystal: "Tetragonal",
      group: "Rutile",
      lustre: "Adamantine",
      ri: "2.00 – 2.10",
      optic: "U+",
      colour: { en: "Colourless, White, Grey, Yellow, Red", si: "අවර්ණ, සුදු, අළු, කහ, රතු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.098",
      sg: "6.95",
      hardness: "6½",
      dispersion: "0.071",
      dichroism: { en: "Weak", si: "දුර්වලයි" },
      transparency: { en: "Transparent to Opaque", si: "පාරදෘශ්‍ය සහ පාරාන්ධ" },
      locality: { en: "Found together with metamict allanite. Gowuvahela, Badulla.", si: "මෙටමික්ට් ඇලනයිට් සමඟ හමු වී ඇත. ගොවුවාහෙල, බදුල්ල." },
      discoverer: "",
      comments: { en: "A rare gemstone. Greek 'kassiteros' = tin.", si: "දුර්ලභ මැණික් ගලකි." },
      year: "1832"
    }
  },
  {
    id: "celestine",
    no: 19,
    swatch: "#A8CCE6",
    name: { en: "Celestine", si: "සෙලීස්ටයින්" },
    group: "Barite",
    fields: {
      formula: "SrSO4",
      composition: "Strontium Sulphate",
      crystal: "Orthorhombic",
      group: "Barite",
      lustre: "Vitreous",
      ri: "1.623 – 1.633",
      optic: "B+",
      colour: { en: "Pale blue and colourless", si: "ලා නිල්, සහ අවර්ණ" },
      absorption: "",
      inclusions: "",
      birefringence: "0.010",
      sg: "4.00",
      hardness: "3½",
      dispersion: { en: "Weak", si: "දුර්වලයි" },
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Madagascar", si: "මැඩගස්කරය" },
      discoverer: "",
      comments: { en: "Has 2 cleavages. Shows a white-blue glow under ultraviolet light. Crystals form inside geodes. Latin 'coelestis' – from its pale blue colour.", si: "පැති 2කට පැළුම ඇත. පාරජම්බුල කිරණ තුළ සුදු-නිල් දීප්තිය ඇත. ගෙඩියක් තුල ස්ඵටික පිහිටා ඇත." },
      year: "1791"
    }
  },
  {
    id: "chondrodite",
    no: 20,
    swatch: "#B5502A",
    name: { en: "Chondrodite", si: "කොන්ඩ්‍රොඩයිට්" },
    group: "Humite",
    fields: {
      formula: "Mg(OH,F)2Mg2(SiO4)",
      composition: "Magnesium, Fluorine, Silicate",
      crystal: "Monoclinic",
      group: "Humite",
      lustre: "Adamantine",
      ri: "1.59 – 1.64",
      optic: "B-",
      colour: { en: "Orange, Red", si: "තැඹිලි, රතු" },
      absorption: "",
      inclusions: "",
      birefringence: "0.028 – 0.034",
      sg: "3.23",
      hardness: "6½",
      dispersion: "0.071",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Tilley Foster Mine, NY", si: "Tilley Foster Mine, NY" },
      discoverer: "d'Ohsson",
      comments: { en: "Orange-red chondrodite occurs on the surface of white dolomite rock. Balangoda. Greek 'granule' – in allusion to its occurrence as isolated grains.", si: "ඩොලමයිට් (සුදු) ගල මතුපිට ක්‍රොන්ඩ්‍රොඩයිට් තැඹිලි රතු වර්ණය පිහිටා ඇත. බලංගොඩ." },
      year: "1817"
    }
  },
  {
    id: "chrysoberyl",
    no: 21,
    swatch: "#C7C24A",
    name: { en: "Chrysoberyl", si: "කනක" },
    group: "Chrysoberyl",
    fields: {
      formula: "BeAl2O4",
      composition: "Beryllium, Aluminate",
      crystal: "Orthorhombic",
      group: "Chrysoberyl",
      lustre: "Vitreous",
      ri: "1.746 – 1.756",
      optic: "B+",
      colour: { en: "Green, Yellow, Greenish brown, Alexandrite green; alexandrite shows a red colour in artificial light", si: "කොළ, කහ, කොළ දුඹුරු, පසිංගල් කොළ; Alexandrite කෘතිම ආලෝකය තුල රතු වර්ණය ගෙනදේ" },
      absorption: {
        en: "Chrysoberyl: due to iron, a broad band at 4440 Å. Alexandrite: chromium – strong double at 6805/6875; weak thin lines at 6650, 6550, 6490, 6400–5500.",
        si: "කනක - යකඩ නිසා පලල් තිරුවක් 4440Å ඇත. පසිංගල් - ක්‍රෝමියම් - double - 6805/6875 ප්‍රබලය. දුර්වල හීන් රේඛා 6650, 6550, 6490, 6400 - 5500 ඇත."
      },
      inclusions: "",
      birefringence: "0.009",
      sg: "3.75",
      hardness: "8½",
      dispersion: "0.015",
      dichroism: { en: "Strong. Alexandrite: red / green", si: "ප්‍රබලය පසිංගල් රතු / කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Alexandrite occurs with mica deposits – a very valuable gemstone. Ural Mountains (Russia), Madagascar, Sri Lanka, Brazil.", si: "මයිකා නිධි සමග පසිංගල් හමුවේ ඉතා වටිනා මැණික් ගලකි. උරල් කඳු රුසියාව, මැඩගස්කරය, ශ්‍රී ලංකාව, බ්‍රසීලය." },
      discoverer: "",
      comments: { en: "Green-yellow colour (vanadium chrysoberyl). A 475 ct green-yellow cut and polished chrysoberyl has been found (Ravi Gems). Name from Greek 'golden' + 'beryl'; alexandrite named after Tsar Alexander II of Russia (1833).", si: "කොළ කහ වර්ණය (වැනේඩියම් කනක)" },
      year: "1790"
    }
  },
  {
    id: "natural-cobalt-spinel",
    no: 22,
    swatch: "#3C5FC4",
    name: { en: "Natural Cobalt Spinel", si: "ස්වභාවික කොබෝල්ට් කිරිංචි" },
    group: "Spinel",
    fields: {
      formula: "MgAl2O4+Co",
      composition: "Cobalt, Magnesium, Aluminate",
      crystal: "Cubic",
      group: "Spinel",
      lustre: "Vitreous",
      ri: "1.715 / 1.718",
      optic: "B+",
      colour: { en: "Electric blue; colour-change (red) stones also occur", si: "ඉලෙක්ට්‍රික් නිල් වර්ණ වෙනස්වන (රතු) ගල් ද ඇත." },
      absorption: { en: "3 strong lines: 623, 597 (broad); 579, 544, 480 nm (strong line due to iron)", si: "ප්‍රබල රේඛා 3ක් ඇත. 623, 597 (මහත) 579, 544, 480, nm (යකඩ නිසා ප්‍රබල රේඛාවක් ඇත.)" },
      inclusions: { en: "2-phase fluid trails", si: "2 - Phase ද්‍රව තාරායම්" },
      birefringence: "",
      sg: "3.52",
      hardness: "8",
      dispersion: "0.020",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Okkampitiya – a collection of cobalt spinel crystals, weight 2.20 kg (museum, Ratnapura). An identification report was given by the author.", si: "ඔක්කම්පිටිය - කොබෝල්ට් කිරිංචි ස්ඵටික එකතුවක්. බර 2.20Kg මිහිමුසියම්, රත්නපුර. කර්තා විසින් හඳුනාගැනීමේ වාර්තාව දී ඇත." },
      discoverer: "Dr. Dunil Palitha Gunasekara (Gemmologist), 1980",
      comments: { en: "The refractive index of synthetic cobalt spinel is 1.722. The largest cut cobalt spinel, 41.65 ct, was examined by the author – a rare blue gemstone.", si: "කෘතිම කොබෝල්ට් කිරිංචි හි වර්තන අංකය 1.722 කි" },
      year: "1983"
    }
  },
  {
    id: "cordierite-iolite",
    no: 23,
    swatch: "#7A78C8",
    name: { en: "Cordierite – Iolite", si: "කෝඩියරයිට් - අයෝලයිට්" },
    group: "Beryl",
    fields: {
      formula: "(Mg,Fe)2Al4Si5O18",
      composition: "Magnesium, Aluminium, Iron, Silicate",
      crystal: "Orthorhombic",
      group: "Beryl",
      lustre: "Vitreous",
      ri: "1.53 – 1.54",
      optic: "B+",
      colour: { en: "Blue, Violet, Colourless, White", si: "නිල්, දම්, අවර්ණ, සුදු" },
      absorption: { en: "Several lines: 6450, 5930, 5850, 5350, 4920, 4560, 4360, 4260 Å", si: "රේඛා කිපයක් ඇත. 6450, 5930, 5850, 5350, 4920, 4560, 4360, 4260 Å" },
      inclusions: "",
      birefringence: "0.005 – 0.018",
      sg: "2.53 – 2.65",
      hardness: "7",
      dispersion: "0.017",
      dichroism: { en: "Strong, blue / violet", si: "ප්‍රබලය නිල්/ දම්" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Badulla, Sri Lanka.", si: "බදුල්ල, ශ්‍රී ලංකාව." },
      discoverer: "Pierre Louis A. Cordier (1777–1861), French geologist",
      comments: { en: "Single-thread and 6-thread iolite have been found. Iolite: Greek 'ios' (violet) + 'lithos' (stone).", si: "තනි නූල් සහ නූල් 6 අයෝලයිට් හමු වී ඇත." },
      year: "1813"
    }
  },
  {
    id: "corundum",
    no: 24,
    swatch: "#2B4CB8",
    name: { en: "Corundum (Sapphire)", si: "කොරන්ඩම් (සැපයර්)" },
    group: "Corundum – Hematite",
    fields: {
      formula: "Al2O3+Fe,Ti,Cr",
      composition: "Aluminium Oxide + Iron + Titanium, Chromium",
      crystal: "Trigonal (barrel-shaped, dipyramidal, flat tabular)",
      group: "Corundum – Hematite",
      lustre: "Vitreous",
      ri: "1.76 – 1.77",
      optic: "U-",
      colour: {
        en: "Red (ruby), Blue (blue sapphire), Yellow (yellow sapphire), Colourless / White / Blue, Padparadscha (red-yellow mix), Star (6 silver rays), Geuda, Diesel white; heat treatment gives blue colour. Violet, Green, Dark blue, Crow blue.",
        si: "රතු (රූබි) නිල් (Blue Sapphire) රත්නපුෂ්පරාග, පුෂ්පරාග (කහ) අවර්ණ සුදු නිල්, පද්මරාග (Padparadscha) (රතු කහ මිශ්‍ර) ආර්නුල් (රිදී නූල් 6ක් ඇත) ගෙවුඩ, ඩීසල් සුදු පාට, සහ දුම්ගල් පිච්චිමෙන් නිල් වර්ණය ගෙන දෙයි. දම්, කොළ, තද නිල්, කාක නිල"
      },
      absorption: {
        en: "Ruby: strong doublet at 6942/6928; weak lines at 6680, 6592; broad dark absorption in yellow-green. 3 further lines. Blue (iron) / green-blue: 3 lines at 4000, 4600, 4500.",
        si: "රතු කැටයේ ප්‍රබල ඩබ්ලට් 6942/6928 ඇත. දුර්වල රේඛා 6680, 6592 පළල කළු උරාගැනීමක් කහ කොළ හි ඇත. තවද රේඛා 3ක් ඇත. නිල් - අයන් - කොළල නිල් හි රේඛා 3ක් ඇත. 4000, 4600, 4500"
      },
      inclusions: "",
      birefringence: "0.008",
      sg: "3.99 – 4.00",
      hardness: "9",
      dispersion: "0.018",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Corundum crystals occur in marble. Ratnapura district, Elahera, Polonnaruwa, Kataragama, Madagascar, Burma, Africa", si: "මාබල් ගල තුල කොරන්ඩම් ස්ඵටික පිහිටා ඇත. රත්නපුර දිස්ත්‍රික්කය, ඇලහැර, පොලොන්නරුව, කතරගම, මැඩගස්කරය, බුරුමය, අප්‍රිකාව" },
      discoverer: "",
      comments: { en: "Ruby shows red fluorescence under long-wave UV. An 8 ct ruby (Myanmar) was sold for USD 2.2 million. 'Kuruvindam' is the Tamil name for ruby.", si: "පාරජම්බුල කිරණ (LWUV) තුල රතු කැට ප්‍රදීපනයක් පෙන්නුම් කරයි. ක්‍රාත් 8 ක රතු කැටයක් (මියන්මාරය) ඇ. ඩොලර් මිලියන 2.2 විකිණී ඇත. රතු Ruby \"කුරුවින්දම්\" දෙමළ නමකි." },
      year: ""
    }
  },
  {
    id: "danburite",
    no: 25,
    swatch: "#E9DDB8",
    name: { en: "Danburite", si: "ඩැන්බුරයිට්" },
    group: "Lamprophyllite",
    fields: {
      formula: "CaB2Si2O8",
      composition: "Calcium, Boron, Silicate",
      crystal: "Orthorhombic (crystals with sharp edges)",
      group: "Lamprophyllite",
      lustre: "Vitreous",
      ri: "1.630 – 1.636",
      optic: "B-",
      colour: { en: "Colourless, Yellow, Pink, Grey, White, Brown", si: "අවර්ණ, කහ, රෝස, අළු, සුදු, දුඹුරු" },
      absorption: { en: "Rare earth – didymium lines", si: "රෙයා එර්ත් - ඩිමියම් රේඛා ඇත." },
      inclusions: "",
      birefringence: { en: "Weak", si: "දුර්වලය" },
      sg: "3.00",
      hardness: "7",
      dispersion: "0.017",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Found on dolomite rock (Danbury, Connecticut, USA). Burma, Madagascar. Ratnapura district, Polonnaruwa, Bogawantalawa, Kolonna.", si: "ඩොලමයිට් ගල (Danbury, Connectical, USA) මතුපිට හමුවේ. බුරුමය, මැඩගස්කරය. රත්නපුර දිස්ත්‍රික්කය, පොළොන්නරුව, බගවන්තලාව, කොලොන්න" },
      discoverer: "C. U. Shepard",
      comments: { en: "Can be distinguished from similar-looking stones by specific gravity and refractive indices.", si: "පඩියං ගලෙන් වෙන්කර ගත හැකේ වි.ගු. සහ වර්තන අංක වලිනි." },
      year: "1939"
    }
  },
  {
    id: "demantoid-garnet",
    no: 26,
    swatch: "#3FA83A",
    name: { en: "Demantoid Garnet", si: "ඩිමැන්ටොයිඩ් රබහ" },
    group: "Garnet",
    fields: {
      formula: "Ca3Fe2(SiO4)3",
      composition: "Calcium, Iron, Silicate",
      crystal: "Cubic (octahedral, dodecahedral crystals)",
      group: "Garnet (Andradite)",
      lustre: "Adamantine",
      ri: "1.888",
      optic: "",
      colour: { en: "Green", si: "කොළ" },
      absorption: { en: "A strong band at 4430 Å", si: "4430Å හි තද ප්‍රබල රේඛාවක් ඇත." },
      inclusions: { en: "Horse-tail inclusions", si: "Horse - Rail අන්තර්ගතය ඇත." },
      birefringence: "",
      sg: "3.82 – 3.88",
      hardness: "6",
      dispersion: "0.057",
      dichroism: "",
      transparency: { en: "Transparent; high dispersion gives it a high lustre (fire)", si: "පාරදෘශ්‍ය, අපකිරණය වැඩි නිසා අභි ප්‍රභවය ඇත." },
      locality: { en: "Ural Mountains (Russia), Madagascar. Crystals occur on serpentine rock.", si: "උරල් කඳු - රුසියාව, මැඩගස්කරය, සර්පන්ටින් ගල මතුපිට ස්ඵටික සැදි ඇත." },
      discoverer: "V.B.D. Andrada e Silva (1763–1838), Brazilian mineralogist",
      comments: { en: "A fairly expensive gemstone. Green colour is due to chromium. Through a colour filter it appears dark reddish. A rare gemstone. Some stones show anomalous double refraction.", si: "තුඩිය වැඩි මැණික් ගලකි. කොළ වර්ණයක්‍රෝමියම් නිසා සිදු වී ඇත. වෙල්සි පෙරණයෙන් බැලුවිට තද රතු පැහැයට පෙනේ. දුර්ලභ මැණික් ගලකි. සමහර ගල් වල ඇනමෝලස් ද්වි වර්තනයක් පෙන්නුම් කරයි." },
      year: "1868"
    }
  },
  {
    id: "diamond",
    no: 27,
    swatch: "#DCEBF2",
    name: { en: "Diamond", si: "දියමන්ති" },
    group: "",
    fields: {
      formula: "C",
      composition: "Carbon",
      crystal: "Cubic (octahedral, dodecahedral crystals)",
      group: "",
      lustre: "Adamantine",
      ri: "2.418",
      optic: "",
      colour: { en: "Colourless, Yellow, Brown, Pink, Green, Orange, Blue, Dark red", si: "අවර්ණ, කහ, දුඹුරු, රෝස, කොළ, තැඹිලි, නිල්, තද රතු." },
      absorption: { en: "4155, 4785, 4650, 4520, 4350, 4230", si: "4155, 4785, 4650, 4520, 4350, 4230" },
      inclusions: { en: "Crystal / garnet inclusions present", si: "ස්ඵටික රබහ ඇත." },
      birefringence: "",
      sg: "3.52",
      hardness: "10",
      dispersion: "0.044",
      dichroism: "",
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Balibathgoda, Muwagama, Ratnapura – a 6.02 ct octahedral, pale yellow-brown diamond was found. Africa, India, Brazil, Russia.", si: "බලිබත්ගොඩ, මුවගම, රත්නපුර, ක්‍රාත් 6.02 ක අෂ්ඨතල, ලා කහ-දුඹුරු දියමන්ති ස්ඵටිකයක් හමු වී ඇත. අප්‍රිකාව, ඉන්දියාව, බ්‍රසීලය, රුසියාව." },
      discoverer: "",
      comments: {
        en: "The hardest gemstone (10 on the Mohs scale). Has cleavage in one direction: a stone can be split along octahedral planes, which is useful in cutting. An 8 ct polished colourless diamond sold for Rs. 7 crore. A 777 ct rough diamond took 3 years to cut and polish.",
        si: "පැල්ම එක් පැත්තකට ඇත. ඔක්ටාහෙඩ්‍රල් තල අනුව ලේසියෙන් ගල දෙකඩ කළ හැක. කැපීමේ දී එය ප්‍රයෝජනවත් වේ. ක්‍රාත් 8 ක ඔප දැමූ අවර්ණ දියමන්තියක්, රු. කෝටි 7 විකුණා ඇත. ක්‍රාත් 777 අමු දියමන්ති ගලක් කපා ඔප දැමීම සඳහා අවුරුදු 3ක් ගත වී ඇත."
      },
      year: "1868"
    }
  },
  {
    id: "diaspore",
    no: 28,
    swatch: "#C9C79A",
    name: { en: "Diaspore", si: "ඩයස්පෝරි" },
    group: "Diaspore",
    fields: {
      formula: "AlO(OH)+Mn",
      composition: "Aluminium, Manganese Hydroxide Oxide",
      crystal: "Orthorhombic",
      group: "Diaspore",
      lustre: "Vitreous",
      ri: "1.702 – 1.750",
      optic: "B+",
      colour: { en: "Colourless, White, Yellow, Pink, Greenish Brown", si: "අවර්ණ, සුදු, කහ, රෝස, කොළ දුඹුරු (Greenish Brown)" },
      absorption: { en: "3 broad lines: 4710, 4630, 4540 Å", si: "පළල රේඛා 03ක් ඇත. 4710, 4630, 4540Å." },
      inclusions: "",
      birefringence: "0.048",
      sg: "3.39",
      hardness: "7",
      dispersion: "",
      dichroism: { en: "Strong: violet-blue, pale green, pink", si: "ප්‍රබලය, දම් නිල් ලා කොළ, රෝස" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Anatolia, Turkey 1977; Ural, Russia.", si: "Anatolia, Turkey 1977, Ural.Russia." },
      discoverer: "",
      comments: { en: "A foreign stone. A very rare gemstone. Greek 'dias' – to scatter, for its unusual decrepitation before the blowpipe.", si: "පිටරට ගලකි. අති දුර්ලභ මැණික් ගලකි." },
      year: "1801"
    }
  },
  {
    id: "diopside",
    no: 29,
    swatch: "#2E7D32",
    name: { en: "Diopside", si: "ඩයොප්සයිඩ්" },
    group: "Pyroxene",
    fields: {
      formula: "CaMgSi2O6",
      composition: "Calcium, Magnesium, Silicate",
      crystal: "Monoclinic (four-sided prismatic crystals)",
      group: "Pyroxene",
      lustre: "Vitreous",
      ri: "1.670 – 1.700",
      optic: "B+",
      colour: { en: "Green, Yellow, Black, Pale green", si: "කොළ, කහ, කළු, ලා කොළ" },
      absorption: { en: "Chrome-diopside: 2 sharp lines at 508, 505 nm", si: "Chrome - Diopside 2 sharp lines at 508, 505 nm." },
      inclusions: { en: "Horse-tail inclusions", si: "Horse - Rail අන්තර්ගතය ඇත." },
      birefringence: "0.030",
      sg: "3.29",
      hardness: "7",
      dispersion: "",
      dichroism: { en: "Strong: yellow, green", si: "ප්‍රබලය, කහ, කොළ" },
      transparency: { en: "Transparent", si: "පාරදෘශ්‍ය" },
      locality: { en: "Pale green diopside varieties; found at Okkampitiya.", si: "ලා කොළ ඩයොප්සයිඩ් වෛරෝඩි, ඔක්කම්පිටියෙන් හමු වී ඇත." },
      discoverer: "d'Andrada",
      comments: { en: "Greek 'double' + 'appearance'.", si: "Greek - double & appearence" },
      year: "1800"
    }
  },
{
    "id": "dumortierite",
    "no": 30,
    "swatch": "#A52A2A",
    "name": { "en": "Dumortierite[cite: 31, 75]", "si": "ඩියුමෝටියරයිට්[cite: 31, 75]" },
    "group": "Borosilicate[cite: 75]",
    "fields": {
      "formula": "(Al,Fe)7BSi3O18[cite: 75]",
      "composition": "Aluminium, Iron, Borosilicate[cite: 75]",
      "crystal": "Orthorhombic[cite: 75]",
      "group": "Borosilicate[cite: 75]",
      "lustre": "Vitreous[cite: 75]",
      "ri": "1.686 - 1.723[cite: 75]",
      "optic": "B+[cite: 75]",
      "colour": { "en": "Red, Brown[cite: 75]", "si": "රතු, දුඹුරු[cite: 75]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.037[cite: 75]",
      "sg": "3.26 - 3.41[cite: 75]",
      "hardness": "8[cite: 75]",
      "dispersion": "",
      "dichroism": { "en": "Strong: Black, Dark Red, Brown[cite: 75]", "si": "ප්‍රබලය, කළු, තද රතු, දුඹුරු[cite: 75]" },
      "transparency": { "en": "Transparent[cite: 75]", "si": "පාරදෘශ්‍ය[cite: 75]" },
      "locality": { "en": "Ratnapura, Madagascar, Nevada, Arizona[cite: 75]", "si": "රත්නපුර, මැඩගස්කරය, නේවාඩා, ඇරිසෝනා[cite: 75]" },
      "discoverer": "Vincent Eugene Dumortier (1802-1873)[cite: 75]",
      "comments": { "en": "As2O5 1.67 wt% present. Single thread stones also exist. A rare gemstone.[cite: 75]", "si": "As2O5 1.67 wt% ඇත. තනි නූල ඇති ගල් ද ඇත. දුර්ලභ මැණික් ගලකි.[cite: 75]" },
      "year": "1881[cite: 75]"
    }
  },
  {
    "id": "blue-dumortierite",
    "no": 30,
    "swatch": "#3B3B6D",
    "name": { "en": "Blue Dumortierite[cite: 76]", "si": "නිල් ඩියුමෝටියරයිට්[cite: 76]" },
    "group": "Borosilicate[cite: 76]",
    "fields": {
      "formula": "(Al,Fe)7BSi3O18[cite: 76]",
      "composition": "Aluminium, Iron, Borosilicate[cite: 76]",
      "crystal": "Orthorhombic[cite: 76]",
      "group": "Borosilicate[cite: 76]",
      "lustre": "Vitreous[cite: 76]",
      "ri": "1.672 - 1.690[cite: 76]",
      "optic": "B-[cite: 76]",
      "colour": { "en": "Purplish Blue[cite: 76]", "si": "දම් පැහැති නිල් වර්ණය[cite: 76]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fingerprint[cite: 76]", "si": "Fingerprint[cite: 76]" },
      "birefringence": "0.018[cite: 76]",
      "sg": "3.42[cite: 76]",
      "hardness": "8[cite: 76]",
      "dispersion": "",
      "dichroism": { "en": "Strong: Dark Blue, Pale Purplish Blue[cite: 76]", "si": "ප්‍රබලය, තද නිල්, ලා දම් නිල්[cite: 76]" },
      "transparency": { "en": "Transparent[cite: 76]", "si": "පාරදෘශ්‍ය[cite: 76]" },
      "locality": { "en": "Tissamaharama, Passara, Badalkumbura Sri Lanka[cite: 76]", "si": "තිස්මහාරාමය, පස්සර, බඩල්කුඹුර ශ්‍රී ලංකාව[cite: 76]" },
      "discoverer": "Dr. Dunil Palitha Gunasekara (Gemmologist)[cite: 76]",
      "comments": { "en": "Chalky Green under short-wave UV. Contains 1.67wt% arsenic As2O5. Extremely rare gemstone. A 2.0 ct emerald cut blue stone was found in Gintota, Tissamaharama by Mr. Piyasiri.[cite: 76]", "si": "පාරජම්බුල කිරණ කෙටි තරංග තුල Chalky Green. 1.67wt% arsenic As2O5 ඇත. ඉතා දුර්ලභ මැණික් ගලකි. ක්‍රාත් 2.0 එමරල්ඩ් කැපුම ඇති නිල් ගලක් පියසිරි මහතාට ගිංතොට, තිස්සමහාරාමයෙන් හමු වී ඇත.[cite: 76]" },
      "year": ""
    }
  },
  {
    "id": "dunilite",
    "no": 31,
    "swatch": "#9ACD32",
    "name": { "en": "Dunilite[cite: 31, 77]", "si": "ඩුනීලයිට්[cite: 31, 77]" },
    "group": "Olivine[cite: 77]",
    "fields": {
      "formula": "(Mg,Fe,Mn)2SiO4[cite: 77]",
      "composition": "Magnesium, Iron, Manganese, Silicate[cite: 77]",
      "crystal": "Orthorhombic[cite: 77]",
      "group": "Olivine[cite: 77]",
      "lustre": "Vitreous[cite: 77]",
      "ri": "1.677 - 1.718[cite: 77]",
      "optic": "B-[cite: 77]",
      "colour": { "en": "Light Greenish Yellow[cite: 77]", "si": "කොළ මිශ්‍ර කහ[cite: 77]" },
      "absorption": { "en": "Three (3) Strong bands: 524, 493, 470nm[cite: 77]", "si": "ප්‍රබල රේඛා 3 කි. 524, 493, 470nm[cite: 77]" },
      "inclusions": { "en": "Liquid inclusions, crystals (spinel)[cite: 77]", "si": "ද්‍රව තාරායම්, ස්පඨික (කිරිංචි)[cite: 77]" },
      "birefringence": "0.041[cite: 77]",
      "sg": "3.48[cite: 77]",
      "hardness": "6½[cite: 77]",
      "dispersion": "0.020[cite: 77]",
      "dichroism": { "en": "Strong: Yellow / Green[cite: 77]", "si": "ප්‍රබලය කහ කොළ වර්ණය[cite: 77]" },
      "transparency": { "en": "Transparent to translucent[cite: 77]", "si": "පාරදෘශ්‍ය සහ පාරාන්ධ[cite: 77]" },
      "locality": { "en": "Top of Katukubura Mountain, Kolonna, Sri Lanka. Found in a huge white calcite rock alongside ferroedenite and black spinel crystals.[cite: 77]", "si": "කටුකුඹුර කන්ද උඩ, කොලොන්න, ශ්‍රී ලංකාව. විශාල සුදු කැල්සයිට් ගල තුල ඩුනීලයිට් ස්පඨික, පේරෝ එඩිඩ්නයිට්, කළු කිරිංචි ස්ඵටික පිහිටා ඇත.[cite: 77]" },
      "discoverer": "Dr. Dunil Palitha Gunasekera, FGA[cite: 77]",
      "comments": { "en": "Can be distinguished from Peridot and Sinhalite by RI and absorption spectrum. Dunilite is attracted to a magnet.[cite: 77]", "si": "Peridot සහ Sinhalite වලින් වෙන්කරගත හැක. කොන්දමට දුනිලයිට් ගල ඇදගනී[cite: 77]" },
      "year": "1996[cite: 77]"
    }
  },
  {
    "id": "ekanite",
    "no": 32,
    "swatch": "#D2B48C",
    "name": { "en": "Ekanite[cite: 31, 82]", "si": "ඒකනයිට්[cite: 31, 82]" },
    "group": "",
    "fields": {
      "formula": "Ca2(Th,U)Si8O20[cite: 82]",
      "composition": "Calcium, Thorium, Uranium, Silicate[cite: 82]",
      "crystal": "Amorphous[cite: 82]",
      "group": "",
      "lustre": "Vitreous[cite: 82]",
      "ri": "1.597[cite: 82]",
      "optic": "",
      "colour": { "en": "Green, Yellow, Brown, Orange[cite: 82]", "si": "කොළ, කහ, දුඹුරු, තැඹිලි[cite: 82]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "",
      "sg": "3.28[cite: 82]",
      "hardness": "6[cite: 82]",
      "dispersion": "",
      "dichroism": { "en": "Strong: Dark Blue, Pale Purplish Blue[cite: 82]", "si": "ප්‍රබලය, තද නිල්, ලා දම් නිල්[cite: 82]" },
      "transparency": { "en": "Transparent and Opaque[cite: 82]", "si": "පාරදෘශ්‍ය සහ පාරාන්ධ. අතේ තබාගෙන සිටිනවිට තෙරියම් නිසා විදුලියක් වැදුනාක් මෙන් දැනේ.[cite: 82]" },
      "locality": { "en": "Eheliyagoda (yellow), Yakkalamulla - Galle (green), Okkampitiya, Sri Lanka.[cite: 82]", "si": "ශ්‍රී ලංකාවේ ඇහැලියගොඩින් සොයාගෙන ඇත. කහ වර්ණය. යක්කලමුල්ල, ගාල්ල හමු වී ඇත. කොළ වර්ණය. ඔක්කන්පිටිය[cite: 82]" },
      "discoverer": "F.L.D. Ekanayake (Gemmologist)[cite: 82]",
      "comments": { "en": "Highly radioactive gem containing 27% thorium oxide. Rough surface looks like an orange peel. 4-ray and 8-ray stones also exist.[cite: 82]", "si": "පිට කොරොසම දොඩම් ලෙල්ලක් මෙන් පෙනේ. තෙල් ගතියක් ද ඇත. අධික විකිරණශීලී මැණික් ගලකි. 27% ෆෙරියම් ඔක්සයිඩ් ඇත. නූල් 4 සහ නූල් 8 ගල්ද ඇත.[cite: 82]" },
      "year": "1953[cite: 82]"
    }
  },
  {
    "id": "enstatite",
    "no": 33,
    "swatch": "#7E6E5C",
    "name": { "en": "Enstatite[cite: 31, 84]", "si": "එන්ස්ටටයිට්[cite: 31, 84]" },
    "group": "Pyroxene[cite: 84]",
    "fields": {
      "formula": "(Mg,Fe)SiO3[cite: 84]",
      "composition": "Magnesium, Iron, Silicate[cite: 84]",
      "crystal": "Orthorhombic[cite: 84]",
      "group": "Pyroxene[cite: 84]",
      "lustre": "Vitreous[cite: 84]",
      "ri": "1.663 - 1.673[cite: 84]",
      "optic": "B+[cite: 84]",
      "colour": { "en": "Colourless, Brown, Green, Orange[cite: 84]", "si": "අවර්ණ, දුඹුරු, කොළ, තැඹිලි[cite: 84]" },
      "absorption": { "en": "Sharp line at 5060 Å, also 5475 Å[cite: 84]", "si": "තියුණු රේඛාවක් 5060 Å හි ඇත. 5475 Å ඇත.[cite: 84]" },
      "inclusions": { "en": "Fibre-like inclusions; solid and liquid inclusions[cite: 84]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තාරායම්[cite: 84]" },
      "birefringence": "0.010[cite: 84]",
      "sg": "3.22[cite: 84]",
      "hardness": "5½[cite: 84]",
      "dispersion": "0.020[cite: 84]",
      "dichroism": { "en": "Weak[cite: 84]", "si": "දුර්වලය[cite: 84]" },
      "transparency": { "en": "Transparent[cite: 84]", "si": "පාරදෘශ්‍ය[cite: 84]" },
      "locality": { "en": "Kimberley mine (Africa), Burma. Colourless enstatite found in Chandrika Wewa, Embilipitiya.[cite: 84]", "si": "කොළ වර්ණය - කිම්බර්ලි පතලය, අප්‍රිකාව, බුරුමය, අවර්ණ එන්ස්ටටයිට්- චන්ද්‍රිකා වැව, ඇඹිලිපිටිය.[cite: 84]" },
      "discoverer": "Kenngolt[cite: 84]",
      "comments": { "en": "Cleavage in 2 directions. Cat's eye varieties exist. Iron-rich stones are named Bronzite.[cite: 84]", "si": "පැළුම පැති 2 ඇත. වෛරෝඩි ද ඇත. අයන් වැඩි ගලෙහි නම බ්‍රොන්සයිට් Bronzite[cite: 84]" },
      "year": "1801[cite: 84]"
    }
  },
  {
    "id": "epidote",
    "no": 34,
    "swatch": "#556B2F",
    "name": { "en": "Epidote[cite: 31, 85]", "si": "එපිඩෝ[cite: 31, 85]" },
    "group": "Epidote[cite: 85]",
    "fields": {
      "formula": "Ca2(Al,OH)Al2(SiO4)3[cite: 85]",
      "composition": "Calcium, Aluminium, Silicate[cite: 85]",
      "crystal": "Monoclinic[cite: 85]",
      "group": "Epidote[cite: 85]",
      "lustre": "Vitreous[cite: 85]",
      "ri": "1.736 - 1.770[cite: 85]",
      "optic": "B+[cite: 85]",
      "colour": { "en": "Brown-Green, Green, Yellow[cite: 85]", "si": "දුඹුරු-කොළ, කොළ, කහ[cite: 85]" },
      "absorption": { "en": "Strong line at 4550 Å, weak line at 4750 Å[cite: 85]", "si": "ප්‍රබල රේඛාවක් 4550 Å හි ඇත. දුර්වල රේඛාවක් 4750 Å හි ඇත.[cite: 85]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.034[cite: 85]",
      "sg": "3.40[cite: 85]",
      "hardness": "6½[cite: 85]",
      "dispersion": "0.030[cite: 85]",
      "dichroism": { "en": "Strong: Green, Brown, Yellow[cite: 85]", "si": "ප්‍රබලය. කොළ, දුඹුරු, කහ[cite: 85]" },
      "transparency": { "en": "Transparent[cite: 85]", "si": "පාරදෘශ්‍ය[cite: 85]" },
      "locality": { "en": "Kachin Hills - Burma. Madagascar, Sri Lanka.[cite: 85]", "si": "Kachin Hills - Burma. Madagascar, Sri Lanka.[cite: 85]" },
      "discoverer": "Hauy[cite: 85]",
      "comments": { "en": "Clinozoisite: RI 1.724-1.734, DR 0.010 B+[cite: 85]", "si": "Clinozoisite R1: 1.724-1.0734 DR: 0.010 B+[cite: 85]" },
      "year": "1801[cite: 85]"
    }
  },
  {
    "id": "euclase",
    "no": 35,
    "swatch": "#ADD8E6",
    "name": { "en": "Euclase[cite: 31, 86]", "si": "ඉයුක්ලේස්[cite: 31, 86]" },
    "group": "Silicate[cite: 86]",
    "fields": {
      "formula": "Be(Al,OH)SiO4[cite: 86]",
      "composition": "Beryllium, Aluminium, Silicate[cite: 86]",
      "crystal": "Monoclinic[cite: 86]",
      "group": "Silicate[cite: 86]",
      "lustre": "Vitreous[cite: 86]",
      "ri": "1.652 - 1.672[cite: 86]",
      "optic": "B+[cite: 86]",
      "colour": { "en": "Light Blue, Green, Yellow[cite: 86]", "si": "ලා නිල්, කොළ, කහ[cite: 86]" },
      "absorption": { "en": "Weak lines at 4680 Å and 4550 Å[cite: 86]", "si": "දුර්වල රේඛා 2ක් 4680 Å, 4550 Å හි ඇත.[cite: 86]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.020[cite: 86]",
      "sg": "3.10[cite: 86]",
      "hardness": "7½[cite: 86]",
      "dispersion": "0.016[cite: 86]",
      "dichroism": { "en": "Strong: Green, Blue[cite: 86]", "si": "ප්‍රබලය. කොළ, නිල්[cite: 86]" },
      "transparency": { "en": "Transparent[cite: 86]", "si": "පාරදෘශ්‍ය[cite: 86]" },
      "locality": { "en": "Minas Gerais (Brazil), Tanzania, Bavaria, Austria (Dark blue), Zimbabwe.[cite: 86]", "si": "මිනාස් ගර්රයිස්, බ්‍රසීලය, ටැන්සානියාව, බැවේරියා, ඔස්ට්‍රියා - තද නිල්, සිම්බාබ්වේ.[cite: 86]" },
      "discoverer": "Hauy[cite: 86]",
      "comments": { "en": "Perfect cleavage.[cite: 86]", "si": "පැලුම තියුණුය.[cite: 86]" },
      "year": "1792[cite: 86]"
    }
  },
  {
    "id": "ferroaxinite",
    "no": 36,
    "swatch": "#8B8878",
    "name": { "en": "Ferroaxinite[cite: 31, 87]", "si": "ෆෙරෝඇක්සිනයිට්[cite: 31, 87]" },
    "group": "Axinite[cite: 87]",
    "fields": {
      "formula": "HMg,Ca2,BAl(SiO4)3[cite: 87]",
      "composition": "Calcium, Aluminium, Borosilicate[cite: 87]",
      "crystal": "Triclinic[cite: 87]",
      "group": "Axinite[cite: 87]",
      "lustre": "Vitreous[cite: 87]",
      "ri": "1.675 - 1.685[cite: 87]",
      "optic": "B-[cite: 87]",
      "colour": { "en": "Brownish Yellow-Blue[cite: 87]", "si": "දුඹුරු මිශ්‍ර කහ නිල්[cite: 87]" },
      "absorption": { "en": "Sharp lines, broad line at 5120 Å in blue-green region, lines at 4920 Å, 4660 Å[cite: 87]", "si": "හීනි රේඛා, නිල් කොළ ප්‍රදේශයේ 5120 Å පළල රේඛා 4920 Å, 4660 Å හි ඇත[cite: 87]" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 87]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තොරායම්[cite: 87]" },
      "birefringence": "0.010[cite: 87]",
      "sg": "3.29[cite: 87]",
      "hardness": "7[cite: 87]",
      "dispersion": "",
      "dichroism": { "en": "Strong: Olive Green, Violet Blue, Cinnamon Brown[cite: 87]", "si": "ප්‍රබලය. ඔලිව් කොළ, දම් නිල්, කුරුඳු දුඹුරු[cite: 87]" },
      "transparency": { "en": "Transparent[cite: 87]", "si": "පාරදෘශ්‍ය[cite: 87]" },
      "locality": { "en": "New Jersey (USA), France, England, Mexico, Badulla (Sri Lanka).[cite: 87]", "si": "නිව් ජර්සි, ඇමරිකාව, ප්‍රංශය, එංගලන්තය, මෙක්සිකෝ, ශ්‍රී ලංකාවේ බදුල්ල.[cite: 87]" },
      "discoverer": "S. Challer[cite: 87]",
      "comments": { "en": "Red fluorescence under short-wave UV due to manganese.[cite: 87]", "si": "කෙටි තරංග පාරජම්බුල කිරණ තුල රතු ප්‍රදීපනයක් ඇත.(මැන්ගනීස් නිසා)[cite: 87]" },
      "year": "1909[cite: 87]"
    }
  },
  {
    "id": "ferroedenite",
    "no": 37,
    "swatch": "#111111",
    "name": { "en": "Ferroedenite[cite: 31, 88]", "si": "ෆෙරෝචඩිනයිට්[cite: 31, 88]" },
    "group": "Amphibole[cite: 88]",
    "fields": {
      "formula": "Na,Ca2(Fe2+Mg)5(Al,Si7O22)(OH)2[cite: 88]",
      "composition": "Sodium, Calcium, Iron, Magnesium Silicate[cite: 88]",
      "crystal": "Monoclinic[cite: 88]",
      "group": "Amphibole[cite: 88]",
      "lustre": "Vitreous[cite: 88]",
      "ri": "1.658 - 1.678[cite: 88]",
      "optic": "B-[cite: 88]",
      "colour": { "en": "Dark Black[cite: 88]", "si": "තද කළු[cite: 88]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 88]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තාරායම්[cite: 88]" },
      "birefringence": "0.020[cite: 88]",
      "sg": "3.17[cite: 88]",
      "hardness": "6[cite: 88]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 88]", "si": "පාරදෘශ්‍ය[cite: 88]" },
      "locality": { "en": "Katukubura Mountain, Kolonna. Found with Dunilite in white calcite rock.[cite: 88]", "si": "කටුකුඹුර කන්ද උඩ, කොලොන්න, සුදු කැල්සයිට් ගල තුල ඩුනිලයිට් සමග එඩිනයිට් ස්පඨික පිහිටා ඇත.[cite: 88]" },
      "discoverer": "",
      "comments": { "en": "Tested by John I. Koivula, 21 July 1998.[cite: 88]", "si": "Tested by John I. Koivula 21 July 1998[cite: 88]" },
      "year": "1946[cite: 88]"
    }
  },
  {
    "id": "fluorite",
    "no": 38,
    "swatch": "#E0B0FF",
    "name": { "en": "Fluorite[cite: 31, 89]", "si": "ෆ්ලෝරයිට්[cite: 31, 89]" },
    "group": "Anhydrous[cite: 89]",
    "fields": {
      "formula": "CaF2[cite: 89]",
      "composition": "Calcium Fluorite[cite: 89]",
      "crystal": "Cubic[cite: 89]",
      "group": "Anhydrous[cite: 89]",
      "lustre": "Vitreous[cite: 89]",
      "ri": "1.434[cite: 89]",
      "optic": "",
      "colour": { "en": "Colourless, Yellow, Brown, Green, Purple, Pink, Red[cite: 89]", "si": "අවර්ණ, කහ, දුඹුරු, කොළ, දම්, රෝස, රතු[cite: 89]" },
      "absorption": { "en": "Weak lines in green: 6100 Å, 5820 Å, 4450 Å, 4270 Å[cite: 89]", "si": "කොළ දුර්වල රේඛා ඇත. 6100 Å, 5820 Å, 4450 Å සහ 4270 Å ඇත.[cite: 89]" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 89]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තාරායම්[cite: 89]" },
      "birefringence": "",
      "sg": "3.18[cite: 89]",
      "hardness": "4[cite: 89]",
      "dispersion": "0.007[cite: 89]",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 89]", "si": "පාරදෘශ්‍ය[cite: 89]" },
      "locality": { "en": "Namibia, Madagascar, Blue Horn (England), Bandarawela (Sri Lanka).[cite: 89]", "si": "නැමීබියාව, මැඩගස්කරය, Blue Horn එංගලන්තය, ඛණ්ඩාරවෙල[cite: 89]" },
      "discoverer": "",
      "comments": { "en": "World's largest cut colour-change (brown-orange) fluorite weighs 3745.40 ct.[cite: 89, 90]", "si": "ලෝකයේ විශාලතම, කපා ඔප දැමූ වර්ණ වෙනස් වන (දුඹුරු-තැඹිලි) ප්‍රෝරයිට් මැණික් ගල බර ක්‍රාත් 3745.40 කි.[cite: 89, 90]" },
      "year": ""
    }
  },
  {
    "id": "forsterite",
    "no": 39,
    "swatch": "#90EE90",
    "name": { "en": "Forsterite[cite: 31, 91]", "si": "ෆොස්ටියරයිට්[cite: 31, 91]" },
    "group": "Olivine[cite: 91]",
    "fields": {
      "formula": "Mg2(SiO4)[cite: 91]",
      "composition": "Magnesium Silicate[cite: 91]",
      "crystal": "Orthorhombic[cite: 91]",
      "group": "Olivine[cite: 91]",
      "lustre": "Vitreous[cite: 91]",
      "ri": "1.635 - 1.670[cite: 91]",
      "optic": "B+[cite: 91]",
      "colour": { "en": "Light Green, Colourless[cite: 91]", "si": "ලා කොළ, අවර්ණ[cite: 91]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 91]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තාරායම්[cite: 91]" },
      "birefringence": "0.035[cite: 91]",
      "sg": "3.22[cite: 91]",
      "hardness": "6½[cite: 91]",
      "dispersion": "0.020[cite: 91]",
      "dichroism": { "en": "Weak[cite: 91]", "si": "දුර්වලය[cite: 91]" },
      "transparency": { "en": "Transparent[cite: 91]", "si": "පාරදෘශ්‍ය[cite: 91]" },
      "locality": { "en": "Hawaii, New Mexico, Ginigalgoda (Kolonna).[cite: 91]", "si": "Hawaii, New Merico ගිණිගල්ගොඩ, කොලොන්න.[cite: 91]" },
      "discoverer": "A. J. Forster (1739-1806) English Collector[cite: 91]",
      "comments": { "en": "Shows dark green fluorescence under UV light.[cite: 91]", "si": "පාරජම්බුල කිරණ තුල තද කොළ ප්‍රදීපනයක් පෙන්නුම් කරයි.[cite: 91]" },
      "year": "1821[cite: 91]"
    }
  },
  {
    "id": "genthelvite",
    "no": 40,
    "swatch": "#F0E68C",
    "name": { "en": "Genthelvite[cite: 31, 92]", "si": "ගෙන්දල්වයිට්[cite: 31, 92]" },
    "group": "Sodalite[cite: 92]",
    "fields": {
      "formula": "Zn4(Be3Si3O12)S[cite: 92]",
      "composition": "Zinc, Beryllium, Sulphur Silicate[cite: 92]",
      "crystal": "Cubic[cite: 92]",
      "group": "Sodalite[cite: 92]",
      "lustre": "Vitreous[cite: 92]",
      "ri": "1.742[cite: 92]",
      "optic": "B+[cite: 92]",
      "colour": { "en": "Colourless, Yellow, Green, Red[cite: 92]", "si": "අවර්ණ, කහ, කොළ, රතු[cite: 92]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 92]", "si": "කෙඳි මෙන් අන්තර්ගත ඝන ද්‍රව තොරායම්[cite: 92]" },
      "birefringence": "",
      "sg": "3.67[cite: 92]",
      "hardness": "6[cite: 92]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 92]", "si": "පාරදෘශ්‍ය[cite: 92]" },
      "locality": { "en": "Mt. St. Hilaire (Canada), Germany, Russia, Nigeria.[cite: 92]", "si": "Mt.St. Hilaireque, Canada, Germany, Russia, Nigeria.[cite: 92]" },
      "discoverer": "A. L.K.W. Genth (1820-1893)[cite: 92]",
      "comments": { "en": "", "si": "" },
      "year": "1844[cite: 92]"
    }
  },
  {
    "id": "goethite",
    "no": 41,
    "swatch": "#DAA520",
    "name": { "en": "Goethite[cite: 31, 93]", "si": "ගොතයිට්[cite: 31, 93]" },
    "group": "Diaspore[cite: 93]",
    "fields": {
      "formula": "FeO(OH)[cite: 93]",
      "composition": "Iron Oxide[cite: 93]",
      "crystal": "Orthorhombic[cite: 93]",
      "group": "Diaspore[cite: 93]",
      "lustre": "Metallic[cite: 93]",
      "ri": "2.26 - 2.40[cite: 93]",
      "optic": "B-[cite: 93]",
      "colour": { "en": "Brown-Yellow layered stripes[cite: 93]", "si": "දුඹුරු - කහ පාට දෙකට තට්ටු වශයෙන් වයිරම් පිහිටා ඇත[cite: 93]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fibre-like solid and liquid inclusions[cite: 93]", "si": "කෙඳි මෙන් අන්කර්ගත ඝන ද්‍රව තාරායම්[cite: 93]" },
      "birefringence": "0.014[cite: 93]",
      "sg": "4.28[cite: 93]",
      "hardness": "5[cite: 93]",
      "dispersion": "",
      "dichroism": { "en": "Weak[cite: 93]", "si": "දුර්වලය[cite: 93]" },
      "transparency": { "en": "Opaque, Translucent[cite: 93]", "si": "පාරාන්ධ, පාරභාෂක[cite: 93]" },
      "locality": { "en": "England, France, Germany, Russia, Elapatha (Ratnapura).[cite: 93]", "si": "එංගලන්තය, ප්‍රංශය,ජර්මනිය,රුසියාව, ඇලපාත, රත්නපුර.[cite: 93]" },
      "discoverer": "Johann Wolfgang von Goethe (1749-1832) German poet[cite: 93]",
      "comments": { "en": "Strong cleavage. Looks like Tiger Eye with stripes.[cite: 93]", "si": "පැළුම ප්‍රබලය. පෙනුම Tiger Eye මෙනි. වයිරම් ඇත[cite: 93]" },
      "year": "1806[cite: 93]"
    }
  },
  {
    "id": "grandidierite",
    "no": 42,
    "swatch": "#4682B4",
    "name": { "en": "Grandidierite[cite: 31, 94]", "si": "ග්‍රැන්ඩිඩියරයිට්[cite: 31, 94]" },
    "group": "Borosilicate[cite: 94]",
    "fields": {
      "formula": "(Mg,Fe)Al3BSiO9[cite: 94]",
      "composition": "Magnesium, Iron, Aluminium, Borosilicate[cite: 94]",
      "crystal": "Orthorhombic[cite: 94]",
      "group": "Borosilicate[cite: 94]",
      "lustre": "Vitreous[cite: 94]",
      "ri": "1.583 - 1.622[cite: 94]",
      "optic": "B-[cite: 94]",
      "colour": { "en": "Greenish Blue[cite: 94]", "si": "කොල මිශ්‍ර නිල් Greenish Blue[cite: 94]" },
      "absorption": { "en": "One line at 479 nm[cite: 94]", "si": "එක් රේඛාවක් 479mm වල ඇත[cite: 94]" },
      "inclusions": { "en": "Parallel fibers on 2 sides[cite: 94]", "si": "සමාන්තර තද පැති 2ට කෙඳි ඇත[cite: 94]" },
      "birefringence": "0.039[cite: 94]",
      "sg": "2.96[cite: 94]",
      "hardness": "7½[cite: 94]",
      "dispersion": "",
      "dichroism": { "en": "Strong: Blue-Green / Light Yellow / Green-Blue[cite: 94]", "si": "ප්‍රබලය. නිල් කොල / ලා කහ / කොල නිල්[cite: 94]" },
      "transparency": { "en": "Transparent[cite: 94]", "si": "පාරදෘශ්‍ය[cite: 94]" },
      "locality": { "en": "Ginigalgoda (Kolonna, 2003), Madagascar.[cite: 94]", "si": "ගිණිගල්ගොඩ, කොලොන්න 2003. මැඩගස්කරය[cite: 94]" },
      "discoverer": "Alfred Grandidier (1836-1812) French explorer[cite: 94]",
      "comments": { "en": "Cleavage in one direction. A 0.29 ct stone was found in Kolonna, Sri Lanka.[cite: 94]", "si": "පැළුම එක පැත්තකට ඇත. 0.29 ct ගල කොලොන්න ශ්‍රී ලංකාවෙන් හමු වී ඇත.[cite: 94]" },
      "year": "1902[cite: 94]"
    }
  },
  {
    "id": "griceite",
    "no": 43,
    "swatch": "#F5F5F5",
    "name": { "en": "Griceite[cite: 31, 95]", "si": "ග්‍රයි සයිට්[cite: 31, 95]" },
    "group": "Halite[cite: 95]",
    "fields": {
      "formula": "LiF[cite: 95]",
      "composition": "Lithium Fluorite[cite: 95]",
      "crystal": "Cubic[cite: 95]",
      "group": "Halite[cite: 95]",
      "lustre": "Vitreous[cite: 95]",
      "ri": "1.392[cite: 95]",
      "optic": "B+[cite: 95]",
      "colour": { "en": "White[cite: 95]", "si": "සුදු[cite: 95]" },
      "absorption": { "en": "Strong line at 4375 Å, weak lines at 4500, 4330 Å[cite: 95]", "si": "ප්‍රබල රේඛාවක් 4375 Aº වල ඇත. දුර්වල රේඛාවක් 4500, 4330A[cite: 95]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "",
      "sg": "2.62[cite: 95]",
      "hardness": "4½[cite: 95]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Semi-Transparent[cite: 95]", "si": "අර්ධ පාරදෘශ්‍ය[cite: 95]" },
      "locality": { "en": "Poudrette quarry, Mt. St. Hilaire, QUE, Canada.[cite: 95]", "si": "Poudrelte quarry, Mt.st. Hilaraire, QUE, Canada[cite: 95]" },
      "discoverer": "Dr. Joel D. Grice (1946)[cite: 95]",
      "comments": { "en": "Named after the discovering mineralogist's last name.[cite: 95]", "si": "සොයාගත් ඛණිජ විද්‍යාඥයාගේ අග නම යොදා ඇත[cite: 95]" },
      "year": "1989[cite: 95]"
    }
  },
  {
    "id": "gypsum-selenite",
    "no": 44,
    "swatch": "#E5E4E2",
    "name": { "en": "Gypsum-Selenite[cite: 31, 96]", "si": "ගිප්සම් සෙලීනයිට්[cite: 31, 96]" },
    "group": "Gypsum[cite: 96]",
    "fields": {
      "formula": "CaSO4·2H2O[cite: 96]",
      "composition": "Calcium Sulphate[cite: 96]",
      "crystal": "Monoclinic[cite: 96]",
      "group": "Gypsum[cite: 96]",
      "lustre": "Pearly[cite: 96]",
      "ri": "1.520 - 1.530[cite: 96]",
      "optic": "B+[cite: 96]",
      "colour": { "en": "Colourless, White, Grey, Yellow, Red[cite: 96]", "si": "අවර්ණ, සුදු, අළු, කහ, රතු[cite: 96]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.010[cite: 96]",
      "sg": "2.32[cite: 96]",
      "hardness": "2[cite: 96]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Semi-Transparent[cite: 96]", "si": "අර්ධ පාරදෘශ්‍ය[cite: 96]" },
      "locality": { "en": "Italy, Chile, England, Mexico[cite: 96]", "si": "ඉතාලිය, චේලි, එංගලන්තය,මෙක්සිකෝ[cite: 96]" },
      "discoverer": "",
      "comments": { "en": "Single silver thread present. Sharp cleavage in 2 directions. Name known from ancient times.[cite: 96]", "si": "තනි රිදී නූලක් ඇත. පැළුම තියුණුයි. පැති 2ක් ඇත. පුරාණයේ සිට දන්නා නමකි.[cite: 96]" },
      "year": ""
    }
  },
  {
    "id": "hambergite",
    "no": 45,
    "swatch": "#DCDCDC",
    "name": { "en": "Hambergite[cite: 31, 97]", "si": "හැම්බර්ගයිට්[cite: 31, 97]" },
    "group": "Anhydrous Borate[cite: 97]",
    "fields": {
      "formula": "Be2(BO3)(OH,F)[cite: 97]",
      "composition": "Beryllium, Fluorine, Borate[cite: 97]",
      "crystal": "Orthorhombic[cite: 97]",
      "group": "Anhydrous Borate[cite: 97]",
      "lustre": "Vitreous[cite: 97]",
      "ri": "1.553 - 1.625[cite: 97]",
      "optic": "B+[cite: 97]",
      "colour": { "en": "Colourless, White, Grey, Yellow, Red[cite: 97]", "si": "අවර්ණ, සුදු, අළු, කහ,රතු[cite: 97]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.072[cite: 97]",
      "sg": "2.35[cite: 97]",
      "hardness": "7½[cite: 97]",
      "dispersion": "0.015[cite: 97]",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 97]", "si": "පාරදෘශ්‍ය[cite: 97]" },
      "locality": { "en": "Found in hard rock. San Diego, Italy, Russia, Madagascar.[cite: 97]", "si": "කළුගල් තුල හමුවේ. සැන්ඩියාගෝ, ඉතාලිය, රුසියාව, මැඩගස්කරය[cite: 97]" },
      "discoverer": "Axel Hamberg (1863-1933)[cite: 97]",
      "comments": { "en": "Sharp cleavage in one direction.[cite: 97]", "si": "එක්පැත්තකට පැළුම තියුණූය.[cite: 97]" },
      "year": "1890[cite: 97]"
    }
  },
  {
    "id": "herderite",
    "no": 46,
    "swatch": "#FAFAD2",
    "name": { "en": "Herderite[cite: 31, 98]", "si": "හර්ඩියරයිට්[cite: 31, 98]" },
    "group": "Adelite[cite: 98]",
    "fields": {
      "formula": "CaBe(PO4)(F)[cite: 98]",
      "composition": "Calcium, Beryllium, Fluorine, Phosphate[cite: 98]",
      "crystal": "Monoclinic[cite: 98]",
      "group": "Adelite[cite: 98]",
      "lustre": "Vitreous[cite: 98]",
      "ri": "1.591 - 1.624[cite: 98]",
      "optic": "B-[cite: 98]",
      "colour": { "en": "Colourless, Light Yellow, Green, Pink, Purple[cite: 98]", "si": "අවර්ණ, ලා කහ, කොල, රෝස, දම්[cite: 98]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.030[cite: 98]",
      "sg": "2.94[cite: 98]",
      "hardness": "5½[cite: 98]",
      "dispersion": "0.017[cite: 98]",
      "dichroism": { "en": "Weak[cite: 98]", "si": "දුර්වලය[cite: 98]" },
      "transparency": { "en": "Transparent[cite: 98]", "si": "පාරදෘශ්‍ය[cite: 98]" },
      "locality": { "en": "Tin mines in Saxony (Germany), Brazil.[cite: 98]", "si": "ටින් පතලය තුල Saxoney, ජර්මනිය. බ්‍රසීලය[cite: 98]" },
      "discoverer": "S.A.W. Von Herder (1776-1838)[cite: 98]",
      "comments": { "en": "Rare gemstone.[cite: 98]", "si": "දුර්ලභ මැණික් ගලකි[cite: 98]" },
      "year": "1828[cite: 98]"
    }
  },
  {
    "id": "hessonite-garnet",
    "no": 47,
    "swatch": "#FFA500",
    "name": { "en": "Hessonite Garnet[cite: 31, 99]", "si": "ගෝමේද රබහ[cite: 31, 99]" },
    "group": "Garnet[cite: 99]",
    "fields": {
      "formula": "Ca3Al2(SiO4)3[cite: 99]",
      "composition": "Beryllium, Fluorine, Borate[cite: 99]",
      "crystal": "Cubic[cite: 99]",
      "group": "Garnet[cite: 99]",
      "lustre": "Vitreous[cite: 99]",
      "ri": "1.740[cite: 99]",
      "optic": "",
      "colour": { "en": "Yellow, Orange[cite: 99]", "si": "කහ, තැඹිලි[cite: 99]" },
      "absorption": { "en": "4070, 4030 Å[cite: 99]", "si": "4070, 4030A0[cite: 99]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "",
      "sg": "3.40[cite: 99]",
      "hardness": "6½[cite: 99]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 99]", "si": "පාරදෘශ්‍ය[cite: 99]" },
      "locality": { "en": "Kataragama, Kamburupitiya, Matara, Madagascar[cite: 99]", "si": "කතරගම, කඹුරුපිටිය, මාතර, මැඩගස්කරය[cite: 99]" },
      "discoverer": "Werner[cite: 99]",
      "comments": { "en": "Exhibits a syrup-like internal effect.[cite: 99]", "si": "ඇතුලත සිරප් වැනි ලක්‍ෂනයක් පෙන්නුම් කරයි.[cite: 99]" },
      "year": "1811[cite: 99]"
    }
  },
  {
    "id": "hibonite",
    "no": 48,
    "swatch": "#E6E6FA",
    "name": { "en": "Hibonite[cite: 31, 100]", "si": "හිබෝනයිට්[cite: 31, 100]" },
    "group": "Spinel - Aluminium",
    "fields": {
      "formula": "(Ca,Ce)(Al,Ti,Mg)12O19[cite: 100]",
      "composition": "Calcium, Cerium, Aluminium, Titanium, Magnesium Oxide[cite: 100]",
      "crystal": "Hexagonal[cite: 100]",
      "group": "Spinel - Aluminium[cite: 100]",
      "lustre": "Vitreous[cite: 100]",
      "ri": "1.790 - 1.807[cite: 100]",
      "optic": "U-[cite: 100]",
      "colour": { "en": "Colourless, Light Yellow, Green, Pink, Purple[cite: 100]", "si": "අවර්ණ, ලා කහ, කොල, රෝස, දම්[cite: 100]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.017[cite: 100]",
      "sg": "3.84[cite: 100]",
      "hardness": "7½[cite: 100]",
      "dispersion": "",
      "dichroism": { "en": "Strong[cite: 100]", "si": "ප්‍රබලය[cite: 100]" },
      "transparency": { "en": "Transparent[cite: 100]", "si": "පාරදෘශ්‍ය[cite: 100]" },
      "locality": { "en": "Madagascar, Siberia, Russia[cite: 100]", "si": "මැඩගස්කරය, සයිබීරියාව, රුසියාව[cite: 100]" },
      "discoverer": "Paul Hibon, French Prospector[cite: 100]",
      "comments": { "en": "Extremely rare gemstone. Cleavage in one direction (0001).[cite: 100]", "si": "අති දුර්ලභ මැණික් ගලකි. පැළුම එක් පැත්තකට ඇත.(0001)[cite: 100]" },
      "year": "1956[cite: 100]"
    }
  },
  {
    "id": "jadeite-jade",
    "no": 49,
    "swatch": "#00A86B",
    "name": { "en": "Jadeite-Jade[cite: 182]", "si": "ජේඩයිට්-ජේඩ්[cite: 182]" },
    "group": "Pyroxene[cite: 182]",
    "fields": {
      "formula": "Na,Al(Si2O6)[cite: 182]",
      "composition": "Sodium, Aluminium, Silicate[cite: 182]",
      "crystal": "Monoclinic[cite: 182]",
      "group": "Pyroxene[cite: 182]",
      "lustre": "Vitreous[cite: 182]",
      "ri": "1.640 - 1.667[cite: 182]",
      "optic": "B+[cite: 182]",
      "colour": { "en": "Colourless, White, Green, Yellow, Brown, Red, Orange, Purple, Grey, Black[cite: 182]", "si": "අවර්ණ, සුදු, කොළ, කහ, දුඹුරු, රතු, තැඹිලි, දම්, අළු, කළු[cite: 182]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.012 - 0.020[cite: 182]",
      "sg": "3.34[cite: 182]",
      "hardness": "7[cite: 182]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent and Opaque[cite: 182]", "si": "පාරදෘශ්‍ය සහ පාරාන්ධ[cite: 182]" },
      "locality": { "en": "Burma, Russia, China[cite: 182]", "si": "බුරුමය, රුසියාව, චීනය[cite: 182]" },
      "discoverer": "Damour Jade[cite: 182]",
      "comments": { "en": "Imperial jade is extremely rare. Highly expensive. Used for carving figures.[cite: 182]", "si": "ඉම්පීරියල් ජේඩ් අති දුර්ලභයි. මිලෙන් අධිකයි. රූප කැපීම සඳහාද භාවිතා කරයි.[cite: 182]" },
      "year": "1863[cite: 182]"
    }
  },
  {
    "id": "jeremejevite",
    "no": 50,
    "swatch": "#ADD8E6",
    "name": { "en": "Jeremejevite[cite: 183]", "si": "ජෙරමිජිවයිට්[cite: 183]" },
    "group": "Boracite[cite: 183]",
    "fields": {
      "formula": "Al6(BO3)5F3[cite: 183]",
      "composition": "Aluminium, Boron, Fluorite[cite: 183]",
      "crystal": "Hexagonal[cite: 183]",
      "group": "Boracite[cite: 183]",
      "lustre": "Vitreous[cite: 183]",
      "ri": "1.637 - 1.647 and 1.642 - 1.650[cite: 183]",
      "optic": "U-[cite: 183]",
      "colour": { "en": "Colourless, Light Yellow-Brown, Blue[cite: 183]", "si": "අවර්ණ, ලා කහ-දුඹුරු, නිල්[cite: 183]" },
      "absorption": { "en": "One line at 5000 Å[cite: 183]", "si": "එක් රේඛාවක් 5000Aº ඇත.[cite: 183]" },
      "inclusions": { "en": "Fibre-like inclusions and liquid inclusions[cite: 183]", "si": "කෙඳි මෙන් අන්තර්ගතය සහ ද්‍රව තාරායම්[cite: 183]" },
      "birefringence": "0.008 - 0.013[cite: 183]",
      "sg": "3.29[cite: 183]",
      "hardness": "7½[cite: 183]",
      "dispersion": "",
      "dichroism": { "en": "Weak. Brownish Yellow / Light Green-Yellow[cite: 183]", "si": "දුර්වලය. දුඹුරු කහ / ලා කොළ - කහ[cite: 183]" },
      "transparency": { "en": "Transparent[cite: 183]", "si": "පාරදෘශ්‍ය[cite: 183]" },
      "locality": { "en": "First found in Vohitrakanga Madagascar, Namibia, Russia, Germany[cite: 183]", "si": "ප්‍රථමයෙන් හමුවූ ස්ථානය Vohitrakanga මැඩගස්කරය, නැමීබියාව, රුසියාව, ජර්මනිය[cite: 183]" },
      "discoverer": "Pavel V. Jeremejev (1830-1899) Russian mineralogist[cite: 183]",
      "comments": { "en": "Fibre inclusions. Needles.[cite: 183]", "si": "කෙඳි අන්තර්ගතය. Needles[cite: 183]" },
      "year": "1883[cite: 183]"
    }
  },
  {
    "id": "johachidolite",
    "no": 51,
    "swatch": "#FFC125",
    "name": { "en": "Johachidolite[cite: 184]", "si": "ජෝහචිඩොලයිට්[cite: 184]" },
    "group": "Ludwigite[cite: 184]",
    "fields": {
      "formula": "Ca,AlB3O7[cite: 184]",
      "composition": "Calcium, Aluminium, Borate[cite: 184]",
      "crystal": "Orthorhombic[cite: 184]",
      "group": "Ludwigite[cite: 184]",
      "lustre": "Vitreous[cite: 184]",
      "ri": "1.712 - 1.726[cite: 184]",
      "optic": "B+[cite: 184]",
      "colour": { "en": "Colourless, Pink, Blue[cite: 184]", "si": "අවර්ණ, රෝස, නිල්[cite: 184]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "Fibre-like inclusions and liquid inclusions[cite: 184]", "si": "කෙඳි මෙන් අන්තර්ගතය සහ ද්‍රව තාරායම්[cite: 184]" },
      "birefringence": "0.008 - 0.012[cite: 184]",
      "sg": "3.34[cite: 184]",
      "hardness": "7½[cite: 184]",
      "dispersion": "",
      "dichroism": { "en": "Weak. Brownish Yellow / Light Green-Yellow[cite: 184]", "si": "දුර්වලය. දුඹුරු කහ / ලා කොළ - කහ[cite: 184]" },
      "transparency": { "en": "Transparent[cite: 184]", "si": "පාරදෘශ්‍ය[cite: 184]" },
      "locality": { "en": "Name of first discovered place Johachido, Kisshu co, N. Korea[cite: 184]", "si": "ප්‍රථමයෙන් හමුවූ ස්ථානයේ නම Johachido, Kisshu co, N.Korea[cite: 184]" },
      "discoverer": "",
      "comments": { "en": "Has cleavage. Shows strong light blue fluorescence under short-wave UV.[cite: 184]", "si": "පැළුම ඇත. SW-UVL කෙටි පාර ජම්බුල කිරණ වල ප්‍රබල ලා නිල් දීප්තියක් පෙන්වයි[cite: 184]" },
      "year": "1942[cite: 184]"
    }
  },
  {
    "id": "kornerupine",
    "no": 52,
    "swatch": "#556B2F",
    "name": { "en": "Kornerupine[cite: 185]", "si": "කොනරුපීන්[cite: 185]" },
    "group": "Tetrahedral[cite: 185]",
    "fields": {
      "formula": "Mg3Al6(Si,Al,B)5O21(OH)[cite: 185]",
      "composition": "Magnesium, Aluminium, Borosilicate[cite: 185]",
      "crystal": "Orthorhombic[cite: 185]",
      "group": "Tetrahedral[cite: 185]",
      "lustre": "Vitreous[cite: 185]",
      "ri": "1.665 - 1.678[cite: 185]",
      "optic": "B-[cite: 185]",
      "colour": { "en": "Dark Green, Yellow, Brown, Blue, White, Pink, Colourless[cite: 185]", "si": "තද කොළ, කහ, දුඹුරු, නිල්, සුදු, රෝස, අවර්ණ[cite: 185]" },
      "absorption": { "en": "One band at 5030 Å[cite: 185]", "si": "එක් තීරුවක් 5030Aº ඇත.[cite: 185]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.013[cite: 185]",
      "sg": "3.27 - 3.45[cite: 185]",
      "hardness": "6½[cite: 185]",
      "dispersion": "",
      "dichroism": { "en": "Strong. Yellow / Green[cite: 185]", "si": "ප්‍රබලය. කහ / කොළ[cite: 185]" },
      "transparency": { "en": "Transparent[cite: 185]", "si": "පාරදෘශ්‍ය[cite: 185]" },
      "locality": { "en": "Madagascar, Sri Lanka[cite: 185]", "si": "මැඩගස්කරය, ශ්‍රී ලංකාව[cite: 185]" },
      "discoverer": "A.N. Kornerup (1857-1881) Danish Geologist[cite: 185]",
      "comments": { "en": "Sri Lanka RI: 1.668-1.680. Dark silver threaded cat's eye found in Okkampitiya.[cite: 185]", "si": "ශ්‍රී ලංකා RI: 1.668-1.680 තද රිදී නූලක් ඇති මාදු වෛරෝඩි ඔක්කම්පිටියෙන් හමුවී ඇත.[cite: 185]" },
      "year": "1884 by J. Lorenzen[cite: 185]"
    }
  },
  {
    "id": "kyanite",
    "no": 53,
    "swatch": "#0000CD",
    "name": { "en": "Kyanite[cite: 186]", "si": "කයනයිට්[cite: 186]" },
    "group": "Andalusite[cite: 186]",
    "fields": {
      "formula": "Al2SiO5[cite: 186]",
      "composition": "Aluminium, Silicate[cite: 186]",
      "crystal": "Orthorhombic[cite: 186]",
      "group": "Andalusite[cite: 186]",
      "lustre": "Vitreous[cite: 186]",
      "ri": "1.715 - 1.732[cite: 186]",
      "optic": "B-[cite: 186]",
      "colour": { "en": "Colourless, Blue[cite: 186]", "si": "අවර්ණ, නිල්[cite: 186]" },
      "absorption": { "en": "Dark black absorption in yellow-green[cite: 186]", "si": "කහ-කොළ හි තද කළු අවශෝෂණයක් ඇත[cite: 186]" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.017[cite: 186]",
      "sg": "3.69[cite: 186]",
      "hardness": "7 & 5[cite: 186]",
      "dispersion": "0.020[cite: 186]",
      "dichroism": { "en": "Strong. / Purple, Colourless, Cobalt Blue[cite: 186]", "si": "ප්‍රබලය. / දම් අවර්ණ කොබෝල්ට් නිල්[cite: 186]" },
      "transparency": { "en": "Transparent[cite: 186]", "si": "පාරදෘශ්‍ය[cite: 186]" },
      "locality": { "en": "Burma, Kashmir, Bandarawela[cite: 186]", "si": "බුරුමය, කාශ්මීරය, බණ්ඩාරවෙල[cite: 186]" },
      "discoverer": "Werner Greek Kuanos, Dark Blue[cite: 186]",
      "comments": { "en": "Sharp cleavage. Polymorphous - Sillimanite and Andalusite have the same formula Al2SiO5.[cite: 186]", "si": "පැළුම තියුණුය. පොලිමෝපස් - Polymorphous සිලිමනයිට් සහ අන්ඩලුසයිට් එම සූත්‍රය ඇත. Al2SiO5[cite: 186]" },
      "year": "1789[cite: 186]"
    }
  },
  {
    "id": "magnesioaxinite",
    "no": 54,
    "swatch": "#FFB6C1",
    "name": { "en": "Magnesioaxinite[cite: 187]", "si": "මැග්නීසියෝඇක්සිනයිට්[cite: 187]" },
    "group": "Axinite[cite: 187]",
    "fields": {
      "formula": "Ca2MgAl2(BSi4O15)OH[cite: 187]",
      "composition": "Calcium, Magnesium, Aluminium, Borosilicate[cite: 187]",
      "crystal": "Triclinic[cite: 187]",
      "group": "Axinite[cite: 187]",
      "lustre": "Vitreous[cite: 187]",
      "ri": "1.662 - 1.670[cite: 187]",
      "optic": "B-[cite: 187]",
      "colour": { "en": "Light Pink[cite: 187]", "si": "ලා රෝස[cite: 187]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.008[cite: 187]",
      "sg": "3.18[cite: 187]",
      "hardness": "6½[cite: 187]",
      "dispersion": "",
      "dichroism": { "en": "Strong. Pink - Light Blue[cite: 187]", "si": "ප්‍රබලය. රෝස - ලා නිල්[cite: 187]" },
      "transparency": { "en": "Transparent[cite: 187]", "si": "පාරදෘශ්‍ය[cite: 187]" },
      "locality": { "en": "Polonnaruwa, Madagascar, Australia[cite: 187]", "si": "පොළොන්නරුව, මැඩගස්කරය, ඕස්ට්‍රේලියාව[cite: 187]" },
      "discoverer": "Alan Jobbins UK[cite: 187]",
      "comments": { "en": "MgO: 8.00, AlO: 32.30, CaO: 13.55, FeO: 1.56[cite: 187]", "si": "MgO: 8.00, AlO: 32.30, CaO: 13.55, FeO: 1.56[cite: 187]" },
      "year": "1975[cite: 187]"
    }
  },
  {
    "id": "magnetite",
    "no": 55,
    "swatch": "#000000",
    "name": { "en": "Magnetite[cite: 188]", "si": "මැග්නටයිට්[cite: 188]" },
    "group": "Spinel[cite: 188]",
    "fields": {
      "formula": "Fe2+Fe3+2O4[cite: 188]",
      "composition": "Iron Oxide[cite: 188]",
      "crystal": "Cubic[cite: 188]",
      "group": "Spinel[cite: 188]",
      "lustre": "",
      "ri": "2.42[cite: 188]",
      "optic": "",
      "colour": { "en": "Dark Brown, Black[cite: 188]", "si": "තද දුඹුරු, කළු[cite: 188]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.017[cite: 188]",
      "sg": "5.17[cite: 188]",
      "hardness": "5½[cite: 188]",
      "dispersion": "",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Opaque[cite: 188]", "si": "පාරාන්ධ[cite: 188]" },
      "locality": { "en": "Sillu[cite: 188]", "si": "සිල්ලු[cite: 188]" },
      "discoverer": "Magnet, a Greek Shepherd mt.Ida,[cite: 188]",
      "comments": { "en": "Sharp cleavage. A mineral. Strongly attracted to magnets.[cite: 188]", "si": "පැළුම තියුණුය. ඛනිජයකි. කාන්දමට තදින් ඇදේ[cite: 188]" },
      "year": "1845[cite: 188]"
    }
  },
  {
    "id": "malachite",
    "no": 56,
    "swatch": "#008000",
    "name": { "en": "Malachite[cite: 189]", "si": "මැලචයිට්[cite: 189]" },
    "group": "Rosasite[cite: 189]",
    "fields": {
      "formula": "Cu2(CO3)(OH)2[cite: 189]",
      "composition": "Copper Carbonate[cite: 189]",
      "crystal": "Monoclinic[cite: 189]",
      "group": "Rosasite[cite: 189]",
      "lustre": "",
      "ri": "1.655 - 1.909[cite: 189]",
      "optic": "B-[cite: 189]",
      "colour": { "en": "Green with stripes[cite: 189]", "si": "කොළ වයිරම් සහිත[cite: 189]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.254[cite: 189]",
      "sg": "4.05[cite: 189]",
      "hardness": "3½[cite: 189]",
      "dispersion": "",
      "dichroism": { "en": "Normal. Colourless, Yellowish Green, Dark Green[cite: 189]", "si": "සාමාන්‍ය. අවර්ණ, කහ කොළ, තද කොළ[cite: 189]" },
      "transparency": { "en": "Opaque[cite: 189]", "si": "පාරාන්ධ[cite: 189]" },
      "locality": { "en": "Zaire, Namibia, Ural mountains, Russia[cite: 189]", "si": "සයිරෙය, නැමීබියාව, යුරල් කඳු, රුසියාව[cite: 189]" },
      "discoverer": "",
      "comments": { "en": "Also forms in nodular/botryoidal shapes.[cite: 189]", "si": "ගෙඩි ගෙඩි මෙන් ද සෑදී ඇත[cite: 189]" },
      "year": "Name from ancient times. Named after Mallows.[cite: 189]"
    }
  },
  {
    "id": "marialite-scapolite",
    "no": 57,
    "swatch": "#FFD700",
    "name": { "en": "Marialite-Scapolite[cite: 190]", "si": "මාරියල්ලයිට් - ස්කැපොලයිට්[cite: 190]" },
    "group": "",
    "fields": {
      "formula": "Na4(Al3Si9O24)Cl[cite: 190]",
      "composition": "Sodium, Aluminium, Silicate[cite: 190]",
      "crystal": "Tetragonal[cite: 190]",
      "group": "",
      "lustre": "Vitreous[cite: 190]",
      "ri": "1.54 - 1.56[cite: 190]",
      "optic": "U-[cite: 190]",
      "colour": { "en": "Colourless, Purple, Pink, Yellow[cite: 190]", "si": "අවර්ණ, දම්, රෝස, කහ[cite: 190]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "", "si": "" },
      "birefringence": "0.004 - 0.008[cite: 190]",
      "sg": "2.50 - 2.78[cite: 190]",
      "hardness": "6[cite: 190]",
      "dispersion": "0.017[cite: 190]",
      "dichroism": { "en": "", "si": "" },
      "transparency": { "en": "Transparent[cite: 190]", "si": "පාරදෘශ්‍ය[cite: 190]" },
      "locality": { "en": "Kolonna - Sri Lanka - Madagascar[cite: 190]", "si": "කොලොන්න - ශ්‍රී ලංකාව - මැඩගස්කරය[cite: 190]" },
      "discoverer": "Andradde Skapos Shaft[cite: 190]",
      "comments": { "en": "Sharp cleavage.[cite: 190]", "si": "පැළුම තියුණුය[cite: 190]" },
      "year": "1800 Maralite. 1866 Mana Ruse Rath (1830-1888)[cite: 190]"
    }
  },
  {
    "id": "meionite-scapolite",
    "no": 58,
    "swatch": "#F0F8FF",
    "name": { "en": "Meionite - Scapolite[cite: 191]", "si": "මියොනයිට් - ස්කැපොලයිට්[cite: 191]" },
    "group": "",
    "fields": {
      "formula": "Ca4(Al6Si6O24)(CO3,SO4)[cite: 191]",
      "composition": "Calcium, Aluminium, Silicate[cite: 191]",
      "crystal": "Tetragonal[cite: 191]",
      "group": "",
      "lustre": "Vitreous[cite: 191]",
      "ri": "1.556 - 1.590[cite: 191]",
      "optic": "U[cite: 191]",
      "colour": { "en": "Colourless[cite: 191]", "si": "අවර්ණ[cite: 191]" },
      "absorption": { "en": "", "si": "" },
      "inclusions": { "en": "2 Phase inclusion[cite: 191]", "si": "2 Phase inclusion[cite: 191]" },
      "birefringence": "0.034[cite: 191]",
      "sg": "2.78[cite: 191]",
      "hardness": "6[cite: 191]",
      "dispersion": "",
      "dichroism": { "en": "Weak[cite: 191]", "si": "දුර්වලය[cite: 191]" },
      "transparency": { "en": "Transparent[cite: 191]", "si": "පාරදෘශ්‍ය[cite: 191]" },
      "locality": { "en": "Kolonna, Sri Lanka, Myanmar[cite: 191]", "si": "කොලොන්න, ශ්‍රී ලංකාව, මියොන්මාරය[cite: 191]" },
      "discoverer": "Andradde - Skapos - Shaft[cite: 191]",
      "comments": { "en": "1801 Greek Meion, Pyramidal faces, High birefringence. Rare gemstone.[cite: 191]", "si": "1801 Greak Meion, Pyramidal faces, ද්විවර්තනය වැඩිය. දුර්ලභ මැණික් ගලකි.[cite: 191]" },
      "year": "1800[cite: 191]"
    }
  }
];

